When did rainfall make the Nile fertile, causing hunters to settle?
9000 BCE

When were agricultural villages spread across the Nile River Valley?
5000 BCE

`start`-`end` BCE: Start of civilization in `place1` and `place2`
start: 3500
end: 3000
place1: Egypt
place2: Nubia

Nubia is `position` of Egypt.
position: South

`time` BCE: Multiple states merged by `king` (a.k.a. `nickname`) along the Nile, starting Egypt
time: 3100
king: Narmer
nickname: Scorpion King

`time` BCE: `name` shows how Narmer united Egypt by `action`
time: 3150
name: Narmer Palette
action: force

`start`-`end` BCE: `name`, an early Nubian civilization that evolved seperately from Egyptian civilization
start: 3400
end: 3200
name: Ta-seti

What type of government did Egypt have (and early Mesopotamia)?
Theocracy

What type of religion was Egyptian religion?
Polytheistic

The sun god was `sun god`, the god of death was `god of death`, the ideal mother and wife was `ideal mother and wife`
sun god: Re
god of death: Osiris
ideal mother and wife: Isis

Hierarchy was Pharaoh, then `1` (most trusted advisor), `2` which wanted to be must trusted advisor, `3`, `4`, and `5`
1: Vizier
2: High priests and Nobles
3: Officials and Scribes
4: Craftsmen and Artists
5: Laborers, peasants, and slaves

What could people do to change their social class in Egypt (progressive)?
marry up
learn craft

Egyptian cities were `adjective` instead of competing like in Sumer.
adjective: unified

`start`-`end` BCE: Early dynastic period
start: 2920
end: 2575

`start`-`end` BCE: Old Kingdom
start: 2575
end: 2134

`start`-`end` BCE: First Intermediate Period
start: 2134
end: 2040

`start`-`end` BCE: Middle Kingdom
start: 2040
end: 1640

`start`-`end` BCE: Second Intermediate Period
start: 1640
end: 1550

`start`-`end` BCE: New Kingdom
start: 1550
end: 1070

`start`-`end` BCE: Third Intermediate Period
start: 1070
end: 712

`start`-`end` BCE: Late Period
start: 712
end: 332

`object`: Gotten by Napoleon, had same thing 3 times, first in `a`, then `b`, then `c`
object: Rosetta Stone
a: Hieroglyphs
b: Egyptian Script
c: Greek

`name`: God of the Divine order of the Universe, very important for `a` and `b`, kept legitimacy
name: Ma'at
a: beauty
b: balance

2920-2770 BCE: First dynasty, start of `phase`
phase: Early Dynastic Period

2649-2575 BCE: Third dynasty, `king` makes `name` pyramid, first pyramid
king: Djoser
name: step

2575-2465 BCE: Fourth dynasty, beginning of `phase`, made `a` and `b`
phase: Old Kingdom
a: Pyramids of Giza
b: Sphinx

How were pyramids positioned?
aligned with stars

What did shafts in pyramids point to?
Orion

2465-2323 BCE: Fifth dynasty, king was `name`, Pharaoh loses power as `god` becomes popular
name: Unas
god: sun god

`start`-`end` BCE: Less flooding in Egypt, let to upheaval
start: 2250
end: 1950

2323-1250 BCE: Sixth dynasty, kingdom replaced by Nobility, `name` I & II
name: Pepi

2150-2134 BCE: Seventh and eigth dynasties, civil war, anarchy, end of `phase` because loss of `requirement`
phase: Old Kingdom
requirement: food surplus

What was written on in Egypt?
papyrus

2134-2040 BCE: Ninth and tenth dynasties, called `name`, eleventh dynasty at the same time called `name2`, fighting between the two, this time was `phase`
name: Herakleopolitan
name2: Theban
phase: First Intermediate Period

2134-1991 BCE: Eleventh dynasty in Thebes, reunified in `time` BCE, beginning of `phase`, `name` (death god) becomes popular but sun god remains popular
time: 2040
phase: Middle Kingdom
name: Osiris

The Middle Kingdom was not as powerful as the Old Kingdom or New Kingdom, and they were `adjective`.
adjective: isolationist

Who brought back art in the Eleventh dynasty?
Montuhoteps

Where did people go during the Middle Kingdom?
Punt
Nubia

1783-1640 BCE: Thirteenth dynasty, end of `phase` due to last `name` being weak
phase: Middle Kingdom
name: Amenemhet

The fourteenth dynasty ruled through the `a` and `b` dynasties.
a: thirteenth
b: fifteenth

During the Second Intermediate Period, a group named the `name` used `technology` technology to take control, making their capital `city`, but weren't accepted
name: Hyksos
city: Memphis
technology: horse and chariot

1650-1500 BCE: 15th, 16th, 17th dynasties rule at once, was the `phase`
phase: Second Intermediate Period

`time` BCE: Egyptian empire becomes bridge between `south place` and `north place`, rules lots of non-Egyptians and becomes part of the `place` and `place2` international political system, lots of gift exchange.
time: 1500
south place: Africa
north place: Asia
place: Babylonian
place2: Assyrian

1550-1307 BCE: Eighteenth dynasty, beginning of `phase`, Prince `fighter` dies ten years before taking over, his brother `brother` leads
phase: New Kingdom
fighter: Kamose
brother: Ahmose

What did Akhenaten do?
Challenge Amen, god of Thebes

1196-1070 BCE: Twentieth dynasty, end of `phase`
phase: New Kingdom

The New Kingdom was known as the  "`name`" and had lots of `structure` in `place`.
name: Golden Age
structure: Temples
place: Valley of the Kings

Akhenaten was the first `thing`, and made the capital city `city`.
thing: Monotheist
city: Amarna

1070-945 BCE: Twenty-first dynasty, Palestine taken by invaders, corruption splits apart Egypt, Lower Egypt is controlled by `group`, upper egypt is controlled by `group2` people which take control of Amen, beginning of `phase`.
group: Merchant monarchs
group2: military
phase: Third Intermediate Period

945-712 BCE: Twenty-second dynasty, `ethnicity`
ethnicity: Libyan

724-712 BCE: Twenty-third dynasty, `ethnicity`
ethnicity: Libyan

770-675 BCE: Twenty-fifth dynasty, `ethnicity` (Kush) unify Egypt in `time` BCE, marks beginning of `phase`
time: 712
ethnicity: Thebes/Nubian
phase: Late Period

Double `thing`: Two snakes icon worn by `number`th dynasty to show unification of Egypt and Nubia
thing: Uraeus
number: 25

525-404 BCE: Twenty-seventh dynasty (`ethnicity`) because Persians stormed border
ethnicity: Persian

When did Nubia develop an ironworking industry?
500 BCE

380-`end` BCE: Thirtieth dynasty
end: 343

343-332 BCE: Second `name` period
name: Persian

When did Alexander the great take over Egypt?
332 BCE