`person` talks about what is needed for civilization.
person: Robert Carneiro

Robert Carneiro says following is needed for civilization, because it led to innovation like plows and irrigation to get more out of land
high and growing density
congested and competitive society
limited rich land

Competition led to `something`, which a State was more suitable for.
something: warfare

`time` BCE: Uruk [`place`] - Pop: `population`k
time: 3000
place: Mesopotamia
population: 50

`time` BCE: Mohenjo Daro & Harappa [`place`] - Pop: `population`k
time: 2000
place: Indus Valley
population: 40

`time` CE: Teotihuacán [`place`] - Pop: `population`k
time: 500
place: Mesoamerica
population: 150

Cities, unlike villages, were `adjective`
adjective: impersonal

Features of cities?
Administrative capital
Center of culture
Marketplace
Manufacturing

Bottom of hierarchy?
female slaves

Why did Egypt & Indus Valley have less slaves than mesopotamia?
less war

Women were defined by their `x`
x: relationship to a man

Why did civilization bring inequality between genders?
plows require strength
animals far from home
men get money
warfare done by men
inheritance based on men

Female gods were `action` as men became dominant.
action: demoted

In Egypt, women could still `a` and `b`
a: own land
b: have slaves