`start`-`end` BCE: `name` civilization in Peru
start: 3000
end: 1800
name: Norte Chico

Where did Norte Chico get water from, since there was very little rainfall?
andes mountains

How many urban centers were in Norte Chico?
25

What was the biggest urban center in Norte Chico?
Caral

What wasn't in Caral that is normally in civilization?
agriculture
pottery
metallurgy
writing
warfare

Norte Chico cities were `adjective` than Sumer cities.
adjective: smaller

What was the name of the knot-based system used for accounting in Norte Chico?
Quipu

What was traded in Norte Chico?
fish

What plants were grown in Norte Chico?
squash
beans
guava

`start`-`end` BCE: Start of civilization in Indus Valley
start: 2200
end: 2000

Indus Valley Civilization had `adjective` planned cities, `type` agriculture, `language type`.
adjective: elaborately
type: irrigated
language type: written language

What was standardized in Indus Valley Civilization?
weights
measures
architectural styles
bricks

What wasn't in Indus Valley Civilization? [classes, honors for dead]
palaces
temples
elaborate graves
king class
warrior class
political hierarchy

What could have explained Indus Valley Civilizations coordination and complexity without political hierarchy?
early caste system
rule by priests
small republics
state without hierarchy

`time` BCE: Indus Valley abandoned due to `thing` in the soil lowering crop yields, `action` to burn mud bricks, and soil `something that happened to the soil`.
time: 1700
thing: salt
action: deforestation
something that happened to the soil: erosion

What remained from Indus Valley civilization?
ceremonial bathing
incense
ritual fire altars
yoga
clothing
jewelry

Which animals were important in religion in Indus Valley civilization and continued on from it?
bulls
elephants

`start`-`end` BCE: Start of Chinese civilization
start: 2200
end: 2070

`start`-`end` BCE: Xia (shyah) dynasty, had `project` projects
start: 2070
end: 1600
project: flood control

`start`-`end` BCE: Shang dynasty
start: 1600
end: 1046

`name`: Seperate civilization from Chinese but in China
name: Sanxingdui

`time` BCE: `animal` and `metal` technology reaches China and makes the Shang dynasty strong.
time: 1200
animal: horse
metal: bronze

`start`-`end` BCE: Zhou (joh) dynasty
start: 1046
end: 771

Features of chinese religion?
lavish tombs
sacrifice

Chinese Poltical Ideology: Ruler (`ruler name`) is intermediary between `place1` and `place2` and is given power by `name`, but only gets power if he is benevolent and maintains social harmony.
ruler name: Son of Heaven
place1: Heaven
place2: Earth
name: Mandate of Heaven

`start`-`end` BCE: `name` civilization begins in Central Asia (`river` River Valley) and water from nearby Oases
start: 2200
end: 2000
name: Oxus
river: Amu Darya

When were fortified centers in Oxus established?
2000 BCE

What did the fortified centers in Oxus contain?
residential compounds
artisan workshops
temples

Oxus was based on `kind` agriculture and stock raising, but had no `culture type` culture.
kind: irrigation
culture type: literate

Oxus had a `kind` hierarchy.
kind: Aristocratic

Oxus occasionally got goods from these places because it was "Eurasian-wide system of commercial exchange"
China
India
Mesopotamia
Nomads
Siberia

When did Civilization in Oxus end for similar reasons to Indus Valley civilization?
1700 BCE

Where do elements of Oxus civilization show up?
Iran
India
Mediterranean

`time` BCE: Olmec civilization begins west of the `place`
time: 1200
place: Yucatan

When did writing come in the Americas from the Olmec civilization?
900 BCE

What was Olmec made of?
competing chiefdoms

Features of Olmec?
decorated temples
altars
pyramids
tombs of rulers

Olmec is known as "`this`"
this: mother civilization

Features of Olmec that survived?
Mound building
Art styles
Ritual sacrifice
Bloodletting
Rubber ball game

Olmec heads were `count` carving of the rulers (not confirmed) that were `height` feet tall and weighed `weight` tons.
count: 17
height: 8
weight: 24