Enlightenment made religion less
powerful

New thoughts about government led to what age
age of isms

Ideas of enlightenment led to what
Revolutions

`scientist` in 1600s says scientific observation makes things true, not `thing`
scientist: Francis Bacon
thing: religion

`thinker` in 1651 says people live by Social Contract where they give up their freedom to `thing` for protection/liberties
thinker: Hobbes
thing: government

`thinker` says that due to Hobbes' ideas, it is the right/responsibility for people to `do what` against unjust government
thinker: Locke
do what: revolt

Locke says peoples natural rights are
life
liberty
pursuit of property

Locke says `thing` is more important than `old thing` for development of individual
thing: environment
old thing: ancestry

`Person` advocates for tripartite (executive, legislative, judiciary) system in government and praises `thing`
Person: Montesquieu
thing: checks and balances

`Person` famous for criticism of French social structure, appreciated social structure of `place`, wanted religious `thing`
Person: Voltaire
place: England
thing: freedom

`person` advocates for extension of social contract to add `thing`
person: Rousseau 
thing: child education

`person` calls for free trade in response to `thing` and wanted government to refrain from acting on `thing2`, fondation of `system`
person: Adam Smith
thing: mercantilism
thing2: economy
system: capitalism

`religious system`: People believe god made natural laws, but `thing` can explain world, famous author is `author`
religious system: Deism
thing: science
author: Thomas Paine

`ism`: Old social constructs were good, proved by poor conditions caused by urbanization
ism: Conservatism

`thing ism`: Ideal societies can be created where workers are happy in their jobs and people live in good conditions, foundational for `author`
thing ism: utopian socialism
author: Marx

Who established small utopian societies in places (british)?
Robert Owen

Classic `ism`: Want constitution, more `thing`, support `thing2` representation in Britain
ism: liberalism
thing: democracy
thing2: cities

`Person` argues that Women should receive same education as men (1792)
Person: Mary Wollstonecraft

When did women get right to vote
1928

Landmark convention in New York for womens right (1828)
Seneca convention

Ism for freeing slaves
Abolitionism

Slave trade abolished in
180x

No more slave trade led to no more
Slavery

Europe serfdom in Britain ended in `time1`, France in `time2`,  Russia in `time3`
time1: 1574
time2: 1789
time3: 1861

Ism for Jews to get new homeland
Zionism

Person leading Zionism
Theodor Herzl

Ism against Jews
Anti-semitism

Zionism grew until `thing` was founded (had to compete with Ottoman empire, arabs, etc.)
thing: Israel