Way to power factories after Water Frame
steam engine

Steam engine used to power
boats
trains

Products of Second Industrial Revolution (metal, fuel, engine, power, communications)
steel
oil
combustion engine
electricity
phone
radio

Important transportation in US for industrialization (could transport vast resources of US)
Transcontinental railroad

Railroads allow people to move
inside of country