Esquiar
ski

Compartir
share

Atraer
attract

Caer
to fall

Valer
to be worth

Seguir
to follow

Conseguir
to achieve

Venir
to come

Agradecer
be thankful

Crecer
to grow

Lucir
to shine

Merecer
to deserve

Obedecer
to obey

Ofrecer
to offer

Pertenecer
to belong

Traducir
to translate

Producir
to produce

Coger
to catch

Corregir
to correct

Dirigir
to direct

Elegir
to choose

Escoger
to choose

Exigir
to demand

Fingir
to pretend

Proteger
to protect

Recoger
to pick up

Surgir
to spurt

Fluir
to flow

Huir
to flee

Influir
to influence

Colgar
to hang up

Contar
to tell a story

Mostrar
to show

Probar
to prove

Soler
to be accustomed to

Aprobar
to approve

Conmover
to move emotionally

Devolver
to give back

Morder
to bite

Rogar
to beg

Sonar con
to dream of

Bendecir
to bless

Conseguir
to obtain

Sonreir
to smile

Despedir
to fire

Reir
to laugh

Me agoba
overwhelms

Me da igual
I don't care

Despiderse
goodbye

Enojarse
get mad

Acordarse de
remember

Olvidarse
to forget

Irse
to leave

Sentirse
to feel

Acercarse a
get close to

Alejarse de
get away from

Casarse
marry