What does Russia lag behind in
education
infrastructure

Russia external problem
losing wars

Group that changes Russia to become communist
Bolsheviks

Bolsheviks leader
Lenin

Internal problems/conflict in China
Hans vs Manchu
low taxes

Qing overthrown by `person` who has `document`
person: Sun Yat-sen
document: The Three People's Principles

China controlled by
warlords

Ottoman Empire problem
declining economy

Group in Ottoman trying to get reform and turkification
Young turks

Turkish group that creates Turkey with Western ideals
Turkish Nationalists

In `country` revolution, citizens overthrew dictatorship, after 10 years of instability `group` formed that would control Mexico until 2000
country: Mexican
group: Institutional Revolutionary Party