Model for cell where proteins can move around within phospholipid bilayer
fluid mosaic

Nonpolar part of phospholipid
fatty acids

Polar parts of phospholipid
glycerol
phosphate group

Type of molecule that diffuses quickly across membrane
small Nonpolar

Type of molecule that diffuses slowly/doesn't diffuse
polar large

Sodium potassium ion pump uses ATP to bring in `in` and put out `out` to create voltage
in: potassium
out: sodium

Protein that transports molecules in an out in cell membrane
transport protein

Enzymes in cell wall that do things
Enzymatic activity

Protein in cell wall that detects signal molecule and sends it inside the cell
signal transduction

Protein in cell wall that has molecule sticking off for identification
glycoprotein

Proteins in cell wall that join to other cells
intercellular joining

Protein in cell wall that do structure connect to what
extracellular matrix
cytoskeleton

When more kinks in phospholipids what happens to fluidity
increases

What does cholestorol do to fluidity at low temp
increase

What does cholestorl do to fluidity at high temp
decrease

Protein that goes through the membrane
transmembrane protein

Protein that is on the side of the membrane
peripheral protein

Molecules that have hydrophobic and hydrophilic side
amphipathic

Movement of water from low solute to high solute
osmosis

Solution names for osmosis: `higher solute`, `same solute`, `lower solute`
higher solute: hypertonic
same solute: isotonic
lower solute: hypotonic

Diffusion in which molecules just cross the membrane
simple Diffusion

Diffusion in which molecules passively cross through transport protein
facilitated diffusion

Diffusion in which ATP is required to move it
active transport

Protein with hole for ions to go through
channel protein

Protein that changes shape passively to bring things through
carrier protein

Process where cell wall encapsulates a large amount of things and brings it in using ATP
endocytosis

Process where golgi makes a phospholipid-encased set of things that then join with the cell wall, allowing proteins to go in cell wall and things to be secreted
exocytosis

Charge across membrane (created by K-Na pump)
membrane potential

Where cell eats, bringing in large protein or molecule
phagocytosis

Where cell drinks, bringing in ions and other solutes
pinocytosis

Where receptors bind to molecules and bring them into the cell
receptor-mediated endocytosis

Transport where hydrogen ion pumped out and then hydrogen goes in with glucose against glucoses' gradient
cotransport

Main electrogenic pump of plants
proton pump

How plant cell is supposed to be where it has high pressure and in hypotonic solution
turgid

How cell is in isotonic solution
flaccid

What cell undergoes in hypertonic solution
plasmolysis

Thing that solutes go down
concentration gradient

Evidence that cells come from prokaryotes
Plasmids
Double membrane
Divide
Ribosomes

Old idea in which living things like bacteria come from nonliving matter (e.g. rotting meat)
spontaneous generation

What came before cells
vesicles

Process in which cell engulfs mitochondria/plastids and they are mutually beneficial
endosymbiosis