What happens to red blood cells as they mature
lose their nucleus

Process where prokaryotes split into two
binary fission

Scale of electron microscope
0.25nm

Scale of light microscope
0.25um

Small membrane-enclosed transport in eukaryote
vesicle

Tree-like structure that produces macromolecules
smooth er

Circular layers around nucleus used to make things to be secreted studded with ribosomes
rough er

What is in gaps of rough er
unbound ribosomes

Set of membranes that is like a C pointing towards plasma membrane
golgi apparatus

Part of golgi apparatus pointing to rough er
Cis

Part of golgi apparatus pointing to plasma membrane
trans

Organelle with a bunch of lines through it parallel
mitochondria

Organelle that looks sort of like muscle inside
chloroplast

Dark part in nucleus
nucleoli

Pointy rough things on cell
fibrillae

Tail of cell
flagella

Thick part around cell
cell wall

Blocky cells are from what
plant

Irregular cells w/out cell wall are what
plant

Size of bacteria cell
<5um

Size of eukaryote
>10um

Big watery area inside plant cell
central vacuole

Things to label
cell wall
plasma membrane
nucleus
organelles

Domains of bacteria
bacteria
archaea

Eukaryote that isnt animal or plant
protist

Inside liquid of cell
cytosol

Structure and movement of cell comes from what
cytoskeleton

Porous membrane surrounding dna in eukaryote
Nuclear envelope

System including nuclear envelope, golgi apparatus, ER, lysosomes, vacuoles, etc. (membranes inside cell)
endomembrane System

Process in which things are sorted and mature inside golgi apparatus
cisternal maturation

Vesicle that fuses with food vacuoles made in phagocytosis to digest
lysosome

Plant organelles that contain chloroplast
plastids

Organelle that produces hydrogen peroxide and turns it to water to do reactions (e.g. liver)
peroxisomes

Shapes of bacteria cell
rod
capsule
sphere

What do both eukaryotes and prokaryotes have
ribosomes