What can members of a species do
produce fertile offspring

Thing that stops members from reproducing
reproductive isolation

Isolation in different places
habitat isolation

Isolation in different times for breeding
temporal isolation

Isolation in different breeding rituals
behavioral isolation

Isolation where mating isnt physically possible
morphological Isolation

Isolation where reproductive cells dont work with each other
gametic isolation

Isolation where offspring don't work
reduced hybrid viability

Isolation where offpsring work but not fertile
reduced hybrid fertility

Isolation where offspring cant mate with parent species
hybrid breakdown

A group of individuals of the same species living in the same area
population

Group of populations of different species in same area that interact
community

Group of organisms and abiotic factors that interact in one area
ecosystem

Name for plants in ecosystem
autotroph

Things that feed on autotrophs
heterotroph

Levels of ecosystem: `1`, `2`, `3`, `4`
1: primary producer
2: primary consumer
3: secondary consumer
4: tertiary consumer

Decomposers that digest internally
detritovore

Decomposers that digest externaly (e.g. mushrooms)
Saprotroph

Trophic efficiency is normaly how much
10%

Resource that limits the amount of organisms in area (can be biotic or abiotic, e.g. sunlight or predators)
limiting factor

Interaction in which one species consumes the other
predation

Interaction in which herbivore eats part of plant but doesn't kill it
herbivory

Interaction in which one species gets nourishment from host and impairs host
parasitism

Interaction in which both animals benefit from each other
mutualism

Interaction in which one animal benefits and other animal doesn't care
commensalism

Interaction in which animals hurt each other by trying to get resource
competition

The biotic and abiotic resources used by an organism is what
ecological niche

Idea where species that share the same ecological niche will make the other go extinct
competitive exclusion

Niche that includes everywhere species can be
fundamental niche

Niche that only has the places that the species can dominate
realized niche

Species that has an outsized impact on ecosystem when removed
keystone species

Low rainfall and very cold biome
tundra

High rainfall, somewhat low temperature
coniferous forest

Low rainfall, high temperature
desert

A tiny bit of rainfall, high temperature
grassland

Medium rainfall, medium temperature
broadleaf forest

High temperature, high rainfall
tropical forest

Total mass of all organisms, also means total energy
biomass

The sequential change in community following a disruption
ecological succession

Ecological succession in areas with no life, little organic material
primary succession

Ecological succession where major disruption but still a little life and organic material (especially soil)
secondary succession

Stages of succession: `1`, where `1 thing` happens, `2` stages happen with different plants, then `3`
1: pioneer
1 thing: colonization
2: seral
3: climax community

Community that is not allowed to reach climax because of human activity (diversion)
pagioclimax community

Amount of energy produced by primary producers minus energy they use in respiration
NPP

Dramatic increase in production when nutrients added to ecosystem, leads to oxygen depletion and fish dying
eutrophication

Energy used in growth or reproduction out of total energy consumed
production efficiency