What is the process in which energy of excites an electron which leaves, water (electron donor) breaks into H+ and O2
photolysis

What is chlorophyll
pigment

Spectrum that shows wavelengths of light in which energy absorbed: `name`, in chlorophyll this is `low`, `high`
name: absorption Spectrum
low: blue
high: red

Spectrum that shows wavelengths of light that increase reaction rate
action spectrum

Visible light: `left`nm to `right`nm
left: 380
right: 750

Stack of membranes inside of cholroplast with chlorophyll embedded
Thylakoid

(Happends in Thylakoid): Sun excites electron in `place1`, it gets passed to `transport` and the missing electron is replaced with electrons from `chemical`, producing `useful` and `waste`. The excited electron is used to bring in `thing` before it is transferred to `place2`, where it absorbs energy and is passed off to make `useful2`, `enzyme` uses the high useful gradient to make ATP
place1: Photosystem II
transport: electron carrier
chemical: water
useful: H+
waste: O2
thing: H+
place2: Photosystem I
useful2: NADPH
enzyme: ATP Synthase

Liquid inside of Chloroplast
stroma

(Happens in stroma): `name` cycle: Brings in `n...` and `a...` from Thylakoids, brings in `chemical`, first step: `step1` (CO2 incorporated into organic molecules), second step: `step2` (ATP and NADPH used to make 6 G3P), third step: `step3` (1 G3P comes out for sugars, 5 go into organic compounds that need CO2)
name: Calvin
n...: NADPH
a...: ATP
chemical: CO2
step1: Fixation
step2: Reduction
step3: Regeneration

Sugar used for transport: `transport`, Sugar used for storage: `storage`
transport: Sucrose
storage: Starch

Area of leaf where CO2 goes in and O2 comes out
stomata

Area of leaf where products transported
vascular bundle

Photosynthesis: `rC` CO2 + `rH` H20 + light -> `pG` C6H12O6 + `pO` O2 + `pH` H2O
rC: 6
rH: 12
pG: 1
pO: 6
pH: 6

Main pigment for Photosynthesis
chlorophyll A

Accessor pigments (widen usable range of light)
carotenoids
chlorophyll B