Chromosomes in eukaryotes are what
chromatins

Nonreproductive cells are called what (human nonreproductive cells have 46 chromosomes)
somatic cells

Duplicated chromosome has two of what
sister chromatid

Place where is attached centerpoint of cross in X
centromere

Division of nucleus is called what
mitosis

Division of cytoplasm is called what
cytokinesis

Phase where cell is performing function and preparing for mitosis (90% of time)
interphase

Phases of mitosis: `1` (`1 viz`), `2` (`2 viz`), `3` (`3 viz`), `4` (`4 viz`), `5` (`5 viz`)
1: prophase
1 viz: condensed dna
2: prometaphase
2 viz: chromosome shape starts
3: metaphase
3 viz: chrosomes in center
4: anaphase
4 viz: mitotic spindle contracts
5: telophase
5 viz: nucleus divides

What happens at the same time as telophase
cytokinesis

Cell division of bacteria is what
binary fission

In animals and bacteria how do they split (where ring of microfilaments contracts, splitting cell into two)
cleavage

In plants how do cells split
golgi apparatus deposits vesicles to make cell wall

In binary fission where does copying of dna happen and cell split
origin of replication

Phases in interphase: `first`, `second` (`second job`), `third` (`third job`)
first: G1
second: S
second job: duplicate dna and organelles
third: G2
third job: prepare mitotic spindle

Proteins that create "checkpoints" at each stage
cyclins

What do cyclins do at checkpoints
bind with enzymes

What happens if cell doesnt go through G1 checkpoint
stage G0

Proteins released by other cells to stimulate cell division
growth factor

What stops crowded cells from dividing (not present in cancer)
density-dependent inhibition

What stops cells from dividing if they are not anchored (also not present in cancer)
anchorage dependence

Process in which cancer cells go through blood to other parts of body
metastasis

What happens in malignant tumor that doesnt happen in benign tumor
metastasis

Genes that normally stimulate normal cell growth but are altered in viruses, causing cancer
oncogenes

Genes that stop uncontrolled cell growth
tumor-suppressor Genes

How does cancer develop
6 stages of genetic changes

Percent of cells in mitosis in a sample called
mitotic index