Structure for order of amino acids
primary structure

Structure for shape formed by hydrogen bonds between the carbonyl and the amino groups (e.g. beta sheets, alpha helix)
secondary structure

Structure for final shape of protein formed by variable R side chain
tertiary structure

Final structure of multiple proteins combine together
quaternary structure

Protein that contributes to structure like cytoskeleton, ECM, or spider silk
structural protein

Protein that performs a function
functional protein

Term usually used to refer to primary structure of protein
peptide

Bond between amino and carboxyl groups to create protein
peptide bond

Multiple amino acids bonded together to make polymers
polypeptide

Covalent bond that forms between two cysteine molecules
disulfide bridge

Number of amino acids
20

Location of protein synthesis
ribosome

Proteins that catalyze reactions
enzymatic protein

Proteins that help immune system detect and break apart pathogens by binding to antigen
antibody

Proteins used to store nutrients (e.g. egg white)
storage protein

Protein that signals to sell
hormonal protein

Protein that receives signals
receptor protein

Protein that moves
contractile protein

What is the entire set of proteins in a cell/tissue/organism called
proteome

Protein involved in absorbing carbon in photosynthesis
rubisco

Protein that regulates sugar intake
insulin

Glycoprotein that attaches to bacteria to identify pathogens by binding to antigens
immunoglobin

Protein that converts light into electrical signal for vision
rhodopsin

Structural protein found in skin, tendons, bones
collagen

What denatures proteins
temperature
ph

Biological molecule that catalyzes one specific reaction without being used in the process
enzyme

The thing that binds with the enzyme
substrate

Part of the enzyme in which the substrate binds
active site

Result of chemical reaction with reactants in enzyme
products

Model in which shape of substrate matches shape of enzyme
lock and key Model

State in between products and reactants after Activation energy (E_a), unstable
transition state

Model in which enzyme clasps around the substrate when it binds due to changing bonds, stretching the molecule, bringing it into its transition state
induced fit model

Enzyme that breaks sucrose
sucrase

Enzyme that breaks proteins
protease

Enzyme that breaks lipids
lipase

Enzyme that builds DNA
DNA polymerase

Enzyme that can break down proteins in stomach pH
pepsin

Protein that breaks starch
amylase

Reactions that release energy are called
exergonic

Reactions that need energy are called
endergonic

Metals or other inorganic vitamins that facilitate movement of electrons not possible with side chains
cofactors

Thing that mimics substrate, slowing down Enzyme, but reversible by changing its concentration
competitive inhibitor

Thing that binds to the enzyme outside of active site to stabilize inactive shape, irreversibly making it slower or not work
noncompetitive inhibitor

Thing that can bind to enzyme to stabilize active shape
activator molecule

Thing where one activator can make all other subunits active, greatly increasing response
cooperativity

What factors create logarithmic graph where y axis is reaction rate
substrate concentration
enzyme concentration

What factor creates normal distribution graph where y axis is reaction rate
pH

What factor creates left skew where y axis is reaction rate
temperature

Thing where enzymes are put into alginate beads or something else in high concentration (e.g. to make lactose free milk)
immobilized enzymes

What are organic cofactors called
coenzymes

Things that enzyme can change to catalyze
orientation
strain bonds
environment

What regulation is where noncompetitive inhibition is used
allosteric regulation

Regulation where result of a series of enzymes inhibits the first one, allowing a certain amount to be made
feedback inhibition