Force between molecules of water
cohesion

Force betwen molecules of water and other polar molecules
adhesion

Macromolecules: `c and o molecules`, `mostly hydrophobic`, `chains of amino acids`, `other stuff, like sugars but with nitrogen`
c and o molecules: carbohydrates
mostly hydrophobic: lipids
chains of amino acids: proteins
other stuff, like sugars but with nitrogen: nucleic acids

When polymers are broken down with the addition of water
hydrolysis

When polymers are made with the removal of water
dehydration synthesis
condensation

Reactions that make bigger molecules
anabolism

Reactions that make smaller molecules
catabolism

All the reactions that happen in cells
metabolism

Construction of complex compounds from simpler ones
synthesis

OH group
hydoxyl

C=O group called
carbonyl group

When carbonyl group is in middle mollecule is called `middle`, on the end (with an H sticking off) it is `end`
middle: ketone
end: aldehyde

H-C=OH (hydroxyl group on a carbonyl group)
carboxyl group

Property of carboxyl group
acidic

H-N-H on end of molecule
amino group

Property of amino group
basic

-S-H group
sulfhydryl group

Molecules with sulfhydrl group called
thiol

Phosphorus group with 2 Oe (O minus 1), double bond O and single bond O
Phosphate group

Property of phosphate group
acidic

CH3 group that goes on rings and other things
methyl group

What are things with methyl group called
methylated

What type of reaction absorbs energy
anabolism

Molecule with 3 hexagons and a pentagon (lipid)
steroid

Groups in amino acid
carboxyl
amino

Saccharide is what type of molecule
sugar

Bond between sugars
glycosidic

Bond between amino acids
peptide

What molecules follow this format: CxH2xOx
sugar

Sugar in DNA
ribose

Just one monomer sugar
monosaccharide

Common monosaccharides
fructose
glucose
galactose

Common disaccharides
lactose
sucrose
maltose

Plant polysaccharides
starch
cellulose

Animal polysaccharide
glycogen

Branched starch: `branched`, unbranched starch: `unbranched`
branched: amylopectin
unbranched: amylose

Another name for trigylcerides
fat

2 fatty acids + glycerol + phosphate group is what
phospholipid

Base steroid that is used in cell walls
cholestorol

Fatty acid with complete amount of hydrogen
saturated fat

Fatty acid with hydrogen on alternating sides
trans fat

Fatty acid with hydrogen on same side, bent
unsaturated fat

Shapes of sugars (make sure you know what these look like)
linear
ring

Polysaccharide in cell walls
cellulose

Why can't cellulose be digested
beta glycosidic bonds