Rules that A=T and C=G
chargaff's rules

Person that takes x-ray diffraction pictures without proper citations from watson and crick, controversial
rosalind franklin

Pyrimidines
cytosine
thymine
uracil

Purines
adenine
guanine

Which type of base has double ring
purines

Components of nucleotide
nitrogenous base
ribose
phosphate group

Bonds in DNA backbone
covalent

Bonds between bases (complementary base pairing means lengths equal)
hydrogen

Process in which DNA copied to DNA
replication

Process in which DNA converted to RNA
transcription

Process in which RNA converted to proteins
translation

People that discovered DNA shape
Watson
Crick

(Correct) method of replication predicted by Watson and Crick, where each strand after replication has one parent strand and one new strand
semiconservative

Model of replication where one completely old strand and one completely new strand
conservative model

Model of replication where each strand is a mix of old and new
dispersive model

When DNA created in heavy nitrogen and then replicated in light nitrogen, what were layers after two generations (confirms semiconservative)
medium
light

Where does replication begin (bubble goes both ways from here)
origin of replication

Ends of replication "bubble" called
replication fork

Enzyme that splits apart DNA
helicase

Protein that stops split strand of DNA from binding back to the other one
single-strand binding Protein

Protein that stops strain by untwisting
topoisomerase

Which side of ribose is 5'
phosphate group

Thing that starts strand of DNA
RNA primer

What enzyme makes RNA primer
primase

Enzyme that elongates the RNA primer with DNA
DNA Polymerase

Direction DNA goes into DNA Polymerase
3' to 5'

Direction DNA is assembled
5' to 3'

Since DNA can only go one way at origin of replication what is on other half of bubble
Okazaki fragments

Strand with Okazaki fragments
lagging strand

What are gaps in lagging strand joined with
DNA ligase

End of chromosomes that are necessary due to RNA primers
telomeres

Enzyme that makes telomeres longer in bacteria, gametes
telomerase

What does PCR stand for
polymerase chain reaction

First stage of PCR in which strands are separated with heat
denaturation

Second stage of PCR in which strands are cooled to allow primers to form on edges of target sequence
annealing

Third stage of PCR in which DNA polymerase adds nucleotides
extension

Polymerase used in DNA that greatly speeds it up due to its ability to handle the heat of annealing
Taq polymerase

Process that contains transcription and translation (genotype -> phenotype)
gene expression

Pairing rules in DNA: G with `1` and A with `2` and C with `3` and T with `4`
1: C
2: T
3: G
4: A

Site of translation
ribosomes

Result of transcription
messenger RNA

DNA strand used for RNA
template strand

DNA strand used as backup
coding strand

Enzyme that does transcription
RNA polymerase

DNA sequence that RNA polymerase attaches to
promoter

DNA sequence that promotes transcription
TATA Box

End of RNA transcription
polyadenylation sequence

Reading frame of 3 bases called what
codon

Thing that attaches with amino acid and complements codons
tRNA

RNA in ribosomes
rRNA

Part of tRNA that pairs with codon
anticodon

Enzyme that attaches amino acid to tRNA
aminoacyl-tRNA synthetase

Site in ribosome that holds next amino acid
A Site

Site in ribosome that has chain of amino acids connecting
P site

Site in ribosome where tRNA comes out
E site

Order of sites in ribosome
EPA

WHich end of amino acid connects to tRNA
carboxyl end

Stage of translation that brings together a tRNA and first amino acid with small and large ribosomal subunits
initiation

Proteins that do initiation (help find start codon, bring first tRNA and ribosomal subunits, etc.)
initiation factors

Steps of `second stage of translation`: `1`, `2`, `3`
second stage of translation: elongation
1: codon recognition
2: peptide bond formation
3: translocation

Last stage of translation
termination

Molecule used for splitting the ribosome
GTP

Proteins destined for being exported have what, signalling ribosome to attach to Rough ER
signal peptide

Particle that binds to signal peptide
SRP

Complementary bases for RNA: A with `1` and T with `2`
1: U
2: A