What is cell theory
all life comes from cells

7 functions of life
nutrition
metabolism
growth
response
excretion
homeostasis
reproduction

Emergent properties: higher `a` leads to `b`
a: organization level
b: complex behavior

Example of emergent properties
muscle cells vs heart
neurons vs brain

Weird feature about muscle cells
multiple nucleoli

Process in which stem cells become specific
differentiation

Name diseases where stem cells can solve
leukemia
stargardt's disease

Stem cells that can do anything
pluripotent

Stem cells somewhat specialized in adults that can only do some specific things (e.g. make blood)
hematopoietic

Critical feature about cells
SA:V Ratio