Balkan countries to fight for independence from Ottoman Empire
Greece
Serbia

Other balkans freed by `small country` and `big country` in `war name`
small country: Serbia
big country: Russia
war name: Russo-Turkish war

Lots of land given to Native Americans in
Proclamation of 1763

What happened to Cherokee
assimilated with white

Native Americans moved to `state` in `act` after gold discovered
state: Oklahoma
act: Indian Removal Act

`thing`: Would lead to dead native americans coming back tro drive out whites, ended at Wounded Knee Massacre in 1890 (ending Native American revolt)
thing: Ghost dance

Túpac `name`: Descendant of Inca rulers, executed colonial leader and started last widespread native rebellion
name: Amaru II

`person` overthrew Mexican liberal govt. for 3 years to support imperialism and get money
person: Napoleon

Sepoys rebel in 1867 in what?
sepoy mutiny

Educated indian organization that advocated for self-rule
Indian National Congress

Country with 12-year old ruler that resisted European rule for entire time
Vietnam

Phillipines started `revolt name` after wealthy filipinos got `thing` (2 years before Spanish-American war)?
revolt name: Phillipine Revolution
thing: education

After US beats Spanish, what happens to Phillipines (expecting freedom)
goes to America

Transfer of Phillipines starts
Phillipine-American war

People with oldest culture
Aboriginals

Aboriginals protected but what taken away?
land

Maori people in New Zealand (migrated in 1300s) protected from British by
treaty of waitangi

Maori people worried about British, leads to
Maori wars

Powerful West African Islamic empire that used slave trade to grow economy (ended by British)
Sakoto Caliphate

African revolutions also started when they got
western education

Western education in Africa led to
Pan-africanism

Sudanese revolt to restore Islam
mahdist revolt

Last war to get Asante empire after 4 failures, African side led by women
war of the golden stool