Major reason why native population died and Europeans could take over?
disease

What environmental thing reduced because of Columbian exchange?
biodiversity

What technology gave Europeans warfare advantage?
firearms

Major animals brought by Europeans
pig
horse

Major foods brought back to Europe (huge pop. increase)?
potato
corn

Major money products from Americas
silver
sugar
tobacco

What place did most slaves go
South America

African slaves mixed their language with Europeans to create `type` languages, common in `place`
type: Creole
place: Carribean

What community thing did slaves use to survive
music

What environmental thing did Europeans cause in the Americas
deforestation