What were European governments motivated by
religion
gold

European governments gained gold through `system`, where they maximize `maximize` and minimize `minimize`
system: mercantilism
maximize: selling
minimize: buying

What European state led the way in exploration
Portugal

Portugal took over through navy [labor, goods, place]
slave trade
indian ocean
malacca

Portugal tried to take over what place religion-wise
china

Portugal created what kind of empire
trading post empire

British focused on what place
India

Dutch focused on what place
malacca

Spanish focused on what place
Phillipines

Spanish made Americas possible by taking `thing` from `place`
thing: silver
place: Aztecs and Incas

What place bought the silver Spain got
china

French took over what place while searching for Northwest passage to Asia
Canada

French didn't `action` so they had better relations with natives and their colonies grew `way`
action: colonize
way: slowly

English realized they could became naval power when they
destroyed spanish

British settlement in Americas (around same time as Quebec)
Jamestown

Dutch created what colony in Hudson bay while trying to find Northwest Passage
New Amsterdam

New Amsterdam current name is `name` and it benefits from `thing`
name: New York
thing: river trade