Things that contributed to american industrial revolution
organization
transportation
communication
population

When did importing slaves become illegal
1808

After when did immigration from Ireland start (before very little immigration)
1830

Time with huge immigration, population growth, and rapidly expanding cities
1840-1860

Group that fears immigrants and tries to remove catholics from government
know-nothings

Where did the Know-Nothings (now political party) win control
Massachussetts

Device that went in canals
steamboat

Government canal construction project that made Northern farmers unable to compete with Western/southern
Erie Canal

Thing that followed canals as major method of bulk transportation
railroads

Where did railroad funding come from
federal government

By when were railraods dominant
1860

What did railroads due to Northwest dependence on the South
lessen

Method that took over long-distance communication, revolutionizing business organization (with fast railroads)
telegraph

Groups that benefitted from telegraph
railroads
newspapers

New business organization that took over large businesses
corporation

Stop at page 232