Things that contributed to american industrial revolution
organization
transportation
communication
population

When did importing slaves become illegal
1808

After when did immigration from Ireland start (before very little immigration)
1830

Time with huge immigration, population growth, and rapidly expanding cities
1840-1860

Group that fears immigrants and tries to remove catholics from government
know-nothings

Where did the Know-Nothings (now political party) win control
Massachussetts

Device that went in canals
steamboat

Government canal construction project that made Northern farmers unable to compete with Western/southern
Erie Canal

Thing that followed canals as major method of bulk transportation
railroads

Where did railroad funding come from
federal government

By when were railraods dominant
1860

What did railroads due to Northwest dependence on the South
lessen

Method that took over long-distance communication, revolutionizing business organization (with fast railroads)
telegraph

Groups that benefitted from telegraph
railroads
newspapers

New business organization that took over large businesses
corporation

Primary job in Northeast
factory system

Idea that revolutionized manufacturing
interchangeable tools

Major american inventor products
goodyear
howe-singer

Elite group in Northeast that financed early factories
merchant capitalists

System where young women are recruited for factory, payed well, and after a few years they go and start families
Lowell system
Waltham system

In what year do factories start switching from women to lower-payed Irish immigrants
1840

Union between skilled artisans to keep their businesses
National Trades' Union

Court case where unions & strikes made legal
Commonwealth v. Hunt

Homeless people in cities called
paupers

Thing that helped minimize discontent between very unequal social classes
social mobility

Another mobility that was important in reducing discontent
Geographic mobility

Most influential and fastest growing class in America
middle class

Major home device for middle class in 1840s for cooking
cast-iron stove

Distinction between what two things emerged because of industrial revolution
family
work

Idea where women only worry about fashion and homekeeping and get more material wealth but less intellectual wealth
cult of domesticity

Thing that emerged in cities because of the little free time industrial workers had
public leisure

Person who made very successful freak shows
P.T. Barnum

Place where farming primarily took Place
midwest

Inventions by john doe and mccormick in agricultural tools
steel plow
reaper
thresher

Thing that drew together and dominated farm communities
religion