Cotton that stopped the South from changing
short-staple

Thing where slaves and planters move South to grow cotton
Second Middle Passage

Reason that South is thought of as great planters even though few had slaves
aristocracy

Thing southerners called slavery and reason they romanticized it
peculiar insitution

Personality of slaves where they act in deference to white people
Sambo

Thing that southerners say about cotton with idea that if they stopped planting cotton, the world would fall apart, and everyone wants to trade with the south
cotton is king

Feature defining southern women
right to be protected

Magazine that called for Southern economic independence from the North, largely not done
De Bow's Review

Reason white women suffered
slave relationships

General name for yeoman farmers
plain folk

Only people in South that opposed Aristocracy, because they weren't connected to plantation syste
hill folk

Places where slaves liked to be because had more social life
large plantations

What happened to slave population after trade stopped in 1808
decline

Most common slave that could gain freedom buy buying it
urban

Ship where slaves illegally being smuggled to US took over and tried to go to Africa but ended up in US, abolitionists sent back to Africa
Amistad

Slave rebellion led by who where they axe white men and women
Nat Turner

Language using some African and some English that slaves used to communicate with each other
pigdin

Major instrument in slave culture
Banjo

What type of resistance did most slaves used
subtle

Act of freeing slaves
manumission

Person that was planning to bring 1000 rebellious slaves together but they got caught because it leaked
Gabriel Prosser