Cotton that stopped the South from changing
short-staple

Thing where slaves and planters move South to grow cotton
Second Middle Passage

Reason that South is thought of as great planters even though few had slaves
aristocracy

Feature defining southern women
right to be protected

Reason white women suffered
slave relationships

General name for yeoman farmers
plain folk

Only people in South that opposed Aristocracy, because they weren't connected to plantation syste
hill folk

Places where slaves liked to be because had more social life
large plantations

What happened to slave population after trade stopped in 1808
decline

Most common slave that could gain freedom buy buying it
urban

stopped on 262