First great school of American painters
Hudson River school

First great american novelist (1820s-1840s)
James Cooper

Great american novelist that wrote Leaves of Grass in 1855
Walt Whitman

American author that Person that wrote Moby Dick in 1851
Herman Melville

Southern writer that wrote sad stories in 1820-1840s
Edgar Allen Poe

Idea that reason is ability to grasp beauty, understanding is society's view of things
transcendentalists

People that led transcendentalism in US
Ralph Emerson
Henry Thoreau

What moral concept did transcendentalists believe in
environmentalism

Utopian community experiment in 1841-1847 with transcendentalists and everyone doing work for each other
Brook Farm

Person that wrote about Brook Farm
Nathaniel hawthorne

`person` founded Utopian Community in which everyone lives in total equality, called `name`
person: Robert Owen
name: New Harmony

Community in which everyone is married to each other and raise children together
Oneida

Utopian community where gender roles equal and celibacy
Shakers

Mormons founded by `person` who writes book of mormon and calls themselves latter-day saints in 1830
person: Joseph Smith

Successor of Joseph Smith that brings 12000 mormons to a new land after Joseph dies in Illinois because of opposition
Brigham Young

Movement to re-adopt religion started in Second Great Awakening, also wanted to end vice
revivalism

Idea where men don't use hard liquor because it causes vice in society
Temperance

"Science" used to see how good people are for a job by measuring skull size
Phrenology

Medical thing that doctors protested against in 1830s and 1840s, making their reputation low
licensed physicians

First person of Massachussetts board of education, started public education in 1837
Horace Mann

A collection of institutions for disabled people
benevolent empire

Reform movements in 1820s and 1830s produced what for mentally ill
asylums

Reform movements in 1820s and 1830s produced what movement led by Grimkes, Beechers, Susan B. Anthony, Mott, Stanton, Dix
Feminism

First feminist convention in 1848: `name` produced document `document`
name: Seneca Falls convention
document: Declaration of Sentiments and Resolutions

Religion of feminists
quakers

Society that pays masters to free slaves and sends them to Liberia
American Colonization Society

In `newspaper`, `person` writes that slaves need to be freed instantly instead of gradually
newspaper: Liberator
person: William Garrison

Society formed by William Garrison
American Antislavery Society

Problem that many abolitionists had to face, led some to be more moderate
violence

Slave with great speeches that escaped to Massachussetts and then England and led abolitionism
Frederick Douglass

Court case in which government doesn't need to enforce returning slaves to owners
Prigg v. Pensylvania

Popular position in Liberty Party where slavery shouldn't be in new states
Free Soil

Major book by Harriet Beecher Stowe that spread abolitionism
Uncle Tom's Cabin

Violent abolitionist that did uprisings in Kansas and Virginia
John Brown

Idea of one god instead of holy trinity, religious movement
unitarianism

Name for parts of New York where religious movements took place
Burned over district