By what year did the US have basically all of modern day US (besides alaska/hawaii/etc.)
1850

When Americans go to texas due to Mexican govt. bonuses but new dictator comes in, `year`:  `war name` breaks out, Americans led by `leader` gain independence (but are rejected by U.S.)
year: 1836
war name: Battle of San Jacinto
leader: Sam Houston

Place on West claimed by British & Americans but lots of Americans migrate there
Oregon

Where did the middle class people migrating come from
Old Northwest

What does Polk want to do with Texas and Oregon
annex

Oregon compromise was over what parallel with Britain to be top of Oregon
49th

Tension grows with what country after Annexation of Texas
Mexico

`year`: `war` breaks out with Mexico over California and New Mexico, led by `leader`
year: 1846
war: Mexican War
leader: Zachary Taylor

How does America end Mexican war when they beat them in America but they don't surrender
seize mexico city

To end Mexican war, `negotiator` gets `treaty`
negotiator: Nicholas Trist
treaty: Treaty of Guadalape Hidalgo

In 1848 campaign what shakes existing political parties when this party gets a lot of votes
free soil party

Who gets voted after Polk
taylor

When did Gold rush "Forty Niners" come to California
1848

Overwhelming majority of population was what
white men

Bill introduced by old clay to handle conflict over slavery in new states (California, New Mexico, etc.)
compromise of 1850

Person that splits compromise of 1850 "omnibus bill" up and gets it all approved
stephen douglas

Law passed in compromise of 1850 to return slaves, very controversial
fugitive slave act

What is crisis over not accepting any new territory due to slavery called
sectional crisis

Purchase of small strip of mexican territory in 1853 for transcontinental railroad for $10 million
gadsden purchase

Act made by Douglas to create states that a transconinental railroad goes through, but is very controversial because it repeals missouri compromise and split up the political parties
Kansas-Nebraska Act

What party is made from people that oppose Kansas-Nebraska Act from both major parties
Republican party

Person chosen by Democrats because he was not controversial
Franklin Pierce

Movement supported by Pierce where America should conquer parts of western europe
young america

Document by Polk hoping to get Cuba for US but north doesn't want new slave state, controversial
ostend manifesto

Name for the intense guerilla warfare between pro and anti-slavery in Kansas
Bleeding Kansas

Murder by John brown, sons, and co. killing pro-slavery people
Pottawatomie Massacre

Person in Senate that gets beaten by Preston Brooks (from South), becoming a Martyr
Charles Sumner

Beliefs of North
free soil
free labor

Belief by North that South will replace government with Aristocracy
slave power conspiracy

Idea that states should get to choose whether they want slavery
popular sovereignty

Written argument of southern professors in 1834 for slavery
The Pro-Slavery argument

People that wrote the pro-slavery argument called what
southern apologists

Democrat that barely won 1856 elections against Republican and weak whigs + weak know-nothings
Buchanan

View of Republicans
federalist

What is Buchanan's personality, led to more division as economic depression hits North and they become Republican
timid

Economic depression during Buchanan
panic of 1857

Court case in which supreme court decides blacks can't sue because they aren't citizen, makes Missouri Compromise unconstitutional
Dred Scott v. Sandford

Constitution written by pro-slavery people in Kansas but rejected by the majority of population twice
lecompton Constitution

Who does republican party elect for 1858 Illionois congressional against democratic Douglas
Lincoln

What does Lincoln do to be more popular
Lincon-Douglas Debates

Who loses but becomes more popular in the 1858 Illionis congressional elections
Lincoln

Planned violent uprising by John Brown that led to his execution but made Southerners want to secede because they thought govt. did it
Harpers Ferry

Person that leads Republican party to president in 1860 (under 40% because of divisions but split between 4 candidates so he wins)
Lincoln

Process that began after Lincoln's election
disunion