Compromise to fix secession that re-established Missouri Compromise
crittenden compromise

Federal property protected by North off the shore of Carolina
Fort Sumter

Commander of confederate forces
General Beauregard

Year when confederates bombard fort sumter, starting civil war
1861

What did North have that South didn't for war
industry
transportation

What did South have that North didn't
commitment

What did Republican party do during the war (little opposition)
nationalistic economic program

`year`: `act` passed to allow people to gain 160 acres in the west for small fee (promoted development) - North
year: 1862
act: homestead act

Act to sell land for education in North (1862)
Morrill act

Railroad company building from East (chartered by Congress)
Union Pacific Railroad company

Railroad company building from West (chartered by Congress)
Central Pacific

When did transcontinental railroad companies meet and link
1869

`years`: Acts to make National Bank: `acts`
years: 1863-1864
acts: National Bank Acts

What year had first income tax
1861

Thing that mostly financed war
Loans

People opposed to draft by Lincoln
Copperheads

Thing lincoln did to dissenters against war
repression

Person that made propaganda and pictures of the war
Matthew Brady

Thing that leads to Lincoln re-election
victories

`year`: `act` that makes slaves that fight in the war free
year: 1861
act: confiscation act

Year of Emancipation proclamation (war not over, only in the union)
1863

After Emancipation proclamation what did slaves do
Join Union army

Person that makes women be nurses, transforms job of nuring
Dorothea Dix

Thing that states do in Confederacy
resist national government

Thing that happened in confederacy when it tried to finance war
inflation

Who led the strategy of the North
lincoln

What did Union do for Southern exports
blockade

Thing that supported moving soldiers in greater amounts than ever before
railroads

Naval technology used to fight war
ironclad boat

Where did Union win first
west

Person that led Union at the start of the war, bad, removed by Lincoln
McLellan

Place where two important battles occur in East
bull run

Thing that actually caused Northern victory
attrition of South

Victory of what thing led to split within confederacy, turning the war
mississippi

Only good general from Union
Ulysses s. Grant

President of confederates
Jefferson Davis

Person that led Southern military for the whole war
Robert E. Lee

As southern Army slowly dwindles Richmond is overtaken and when does South surrender
1865

Riots over the draft were what
New York City Draft Riots

Amendment ending slavery
13th amendment

Ironclad boats where they kept each other in stalemate, saving Northern blockade
merrimac and monitor

Major general of south, got wounded
Stonewall Jackson

Place where McLellan gives time for Lee to re-organize even though he could've won
antietam creeks

Place grant sieges on his way to Richmond
Viskburg

Where did Davis surrender
Appomattox court house

Place where South tries to invade North, loses, famous battle that turned the tide
Gettysburg

Thing where Johnson A. Sherman destroys Georgia on his march
March to the sea

Infantry in North made up of freed slaves (with white leader)
54th Massachussetts Infantry

Person that was vice president for lincoln for second term, opposed Tennessee seceding
Andrew Johnson