People left displaced by civil war
Southern Whites
Southern Blacks

Organization from congress to help slaves freed from the war
freedmen's bureau

What type of reconstruction policy did lincoln put
lenient

Bill that rejected lincoln's reconstruction states and forced states to make a new constitution with only people that were loyal, remove congress from their debts
Wade-Davis bill

What happened to Wade-Davis bill
veto

When is Lincoln shot
1865

Who takes over after Lincoln
Andrew Johnson

What is Andrew Johnson reconstruction plan like
Wade-Davis bill

When southern states do everything under Andrew Johnson plan or Lincoln plan (presidential reconstruction) what do radicals in congress do
start congressional reconstruction

Thing in South that allows blacks to be fined and forced to work, Freedmen Bureau is extended past 1 year to stop these
Black codes

When was the first civil rights act passed?
1866

What did first civil rights act do
make blacks citizens

Amendment made by first civil rights act
14th Amendment

Election where Johnson supports conservative but is bad so radicals win
1866

What does radical government require
ratification of 14th by black and white loyals

Law enacted by radicals to stop president from removing officials (so that they can keep their radicals in his cabinet)
Tenure of Office act

What do Radicals stop from interfering with reconstruction
supreme court

What do radicals do to Johnson when he dismisses secretary of war even though Tenure of Office act
impeach

Biggest improvement in South from reconstruction
education

Thing where freed slaves worked land given by landlord and gave a share of their profits or crops
sharecropping

Why could blacks not rise out of poverty
no credit

System where local stores give credit to farmers, who have collateral on their crops, get stuck in debt, high rates
crop-lien system

Who gets elected in 1868
Ulysses Grant

How does grant alienate voters
radical

Problem in grant presidency
corruption

Financial crisis during Grant
panic of 1873

Political party created to support paper money during Grant
greenbackers

Major secretary of state during Johnson
William Seward

Major secretary of state during Grant
Hamilton Fish

Economic policy of Seward "seward's folly"
sell alaska

What does hamilton fish resolve (damages from ships during civil war)
alabama claims

Acts that stop groups like KKK from using intimidation on black voters
Enforcement Acts

Enforcement acts (a.k.a KKK Acts) are what Amendment
15th amendment

After 15th amendment what happened to the radicals
declined

Democrat leader in 1876 who wins popular vote but loses
Samuel Tilden

Republican leader that wins 1876 elections (Grant stopped from re-running)
Rutherford Hayes

Thing that Hayes government had to give
democrat concessions

Compromise to try to establish Republican party in south but failed, ended reconstruction
compromise of 1877

Thing that came to the South after reconstruction
factories

Type of workers in southern factories due to casualties from civil war
women

Leader of african american education (slave that became educated)
Booker Washington

Court case allowing segregation
Plessy v. Ferguson

Court case that allowed better schools for Whites
Cumming v. County Board of education

What happened in late 1800s and early 1900s to blacks in the South
disenfranchisement

Laws for disenfranchisement
jim crow Laws

Person that published articles after lynching
Ida Wells

Period where country is tring to be like it was before the war (most of reconstruction and later years)
antebellum period

Scandal in Grant presidency over what company giving stock to officials
credit mobilier