Idea of west before it was frontier
Great American Desert

Difference between ideal version of west and real
inhabited

Most widespread group in west
Plains indians

Group that was most common in New Mexico
Hispanics

What led to Americans in Southwest
Railroads

Person that led angry mexican ranchers to free other mexicans
juan cortina

Name for mexicans in california
californios

People that came for gold but got racially excluded and had to work on Railroads
Chinese

Political machines in Chinatowns led by merchants, helped Chinese in the Chinatowns
Six Companies

Act that banned chinese immigration and naturalization
Chinese Exclusion Act

Acts that provided land for planting trees/watering land/etc.
Timber Culture Act
Desert Land Act

3 industries of west
mining
ranching
commercial farming

Person that had show about wild west that romanticized it and was very popular and famous
buffalo bill cody

Group that raised cattle along the way to eastern markets on grass on the trails
open ranchers

What did open ranchers have to compete with
farmers

Painters of the west
Rocky mountain school

Person that made novels that represented desire to advance to west
Mark Twain

What happened when West fully finished
opportunity lost

Method where native americans moved to fixed size reservations and split up from each other
concentration

Major conflict between Natives and Whites over what resource
Buffalo

Major battle victory for Natives
battle of little bighorn

People leading battle of little bighorn
crazy horse
sitting bull

Most brutal fights with Natives
Apache Wars

Assimilation of Natives run by what
Bureau of Indian Affairs

Act that forces Natives to switch from tribes to individual land ownership
Dawes Act of 1887

What led to decline of farming in west
return to low rainfall

Person that made document that claimed Western expansion made america possible
Frederick Jackson Turner

Person that led natives trying to flee to canada over 1000s of miles while escaping whites but eventually lost
Chief Joseph

Dance that made whites scared because Natives were being spiritual
Ghost Dance

Massacre after Ghost Dance where whites killed natives
wounded knee massacre