Thing that supported growing companies during time of growth
communications

Person that developed process to make steel
Henry Bessemer

Thing that supported trade across oceans
new steam engine

`year`: `person` makes first Oil well in Pennsylvania
year: 1859
person: George Bissell

Person that developed 4-stroke engine
Nicolaus Otto

Year when ford makes car
1895

Year when Wrights make flight
1903

Thing critical to assembly line
interchangeable parts

People that merged railroads to make giants
Cornelius Vanderbilt
James Hill
Collis Huntington

Development of modern corporation relied on what
stocks

Thing where multiple businesses doing same thing combine
horizontal integration

Thing where business buys businesses it relies
vertical integration

Person that did vertical integration
carnegie

Who consolidates oil both vertically and horizontally, becoming a symbol of monopoly (considered good)
rockefeller

Person that introduces idea of trust where corporations sell themselves to get profits of whole trust
jp morgan

Development that allowed companies to buy other companies
holding companies

Andrew Carnegie writes book called what about how rich should help poor
The Gospel of Wealth

Original person that gives lecture about how anyone can become rich
Russell Conwell

Person that writes hundreds of rags to riches novels, spreading the idea
Horatio Alger

Novel that shows female ambition
Little Women

Book that claims government can fix monopolies and that will benefit everyone
Dynamic Sociology

When did erratic economy start with recessions every 5 years
1873

First national labor conflict
railroad strike of 1877

Union for all people that work
knights of labor

Organization for skilled laborers called `name`, striked nationally on `year`
name: AFL
year: 1886

Strike of steelworkers where workers fight and initially win but lose to military, union loses power
homestead strike

Strike in Chicago of car and rail workers where state government won't step in so national government comes in and stops it
pullman strike

Person that led the car workers to collaborate with the rail workers to strike the car company
Eugene Debs

Reason why unions didn't work in late 1800s
corporations too powerful

Idea used to support wealthy capitalists
social darwinism

Idea that workers need to become interchangeable and managers need to be scientific in early 1800s (eventually led to assembly line)
taylorism

Oil company of rockefeller
standard oil

Labor unions that used violence, made unions less popular
molly maguires

Bomb thrown during what strike led to unions being less popular
haymarket bombing

Benefit of stocks
limited liability