Where did migrants for cities come from
Eastern farms

Difference between American immigrants and other countries
diverse

Organizations to stop immigration
American Protective Association
Immigration Restriction League

New thing made in cities in 1860s
parks

Movement to make symmetrical and orderly cities in architects like Daniel Burnham
city beautiful movement

Place where poor live in cities
tenement

Person that makes book about tenement life
Jacob Riis

Major structure that changed cities transportation
brooklyn bridge

Thing that led to fire departments & new construction techniques
boston and chicago fires 1871

`year`: `government organization` to stop dangers of city to environmental and human heatlth
year: 1912
government organization: Public Health Service

Story about women being hurt in cities (Sister Carrie) written by
Theodore Dreiser

What did political machines need to get
votes

Most corrupt and large political machine was led by `person` in `machine`
person: William M. Tweed
machine: Tammany Hall

Thing that changed in cities in early 1900s
consumerism

New type of store made in early 1900s that made consumerism more popular
department stores

Year of first American baseball league
1876

Theater that has a variety of spectacles
vaudeville

Biggest example of public entertainment
coney island

Most powerful newspaper owner, powered by telegraph
William R Hearst

Massive monopoly over all telephone systems, made possible by "repeater"
AT&T

Person that writes about oppression of women and gets bullied
Kate Chopin

School  of art that makes very naturalist portrayals of social realities, finally beats Europe
Ashcan school

Famous art show in New York
armory show

Thing that made rift between liberal urbans and conservative rurals
darwinism

`person` published `idea` where everything needs to be tested if it worked - followed scientific inquiry
person: William James
idea: pragmatism

Thing that allowed universities to develop science with real-world impact and become respected
donations from monopolies

When do doctors accept germ theory and scientific inquiry
early 1900s

Ethnic enclaves called what
ghettoes

Organization that encourage people to only buy products with its label (made with fair working conditions)
National Consumers League