Thing that remained throughout 19th century
party stability

Reason for intense loyalty to political parties
geographical region

What are the 100k people president appoint called
patronage

What president had to deal with competing factions for patronage, leading to neither reelecting him
Rutherford Hayes

Faction that supports no change, political machine and party-based patronage
stalwarts

Faction that supports reform
half-breeds

When President James Garfield shot by Stalwart for his half-breed he is replaced by what vice president that was a stalwart
Chester Arthur

What does Chester Arthur do when he becomes president (unexpect/unloyal to his faction)
civil service exam

Act that did civil service exam
Pendleton Act of 1883

Person that embodies era of no government intervention, tries to reduce tariffs but this becomes election issue
Grover Cleveland

Thing that people want federal government to confront
antitrust

Case in which federal government says state regulation of railroads unconstitutional
wabash

Federal antitrust act that is not enforced
Sherman Act of 1890

Farmers that file the wabash Case
granges

Commission created to regulate railroads but little enforced
Interstate Commerce Commission

Group of farmers that replaces granges
Farmers' Alliance

When the groups combine they make people's party, called what
populist party

Thing that starts Panic of 1893
failure of railroads

When silver is not used to back dollar what is it called (because it was worth more as silver, but stopped being that)
Crime of '73

What do populists want
more money through silver

`person` that gives `name` speech is nominated for democrats, supports silver like populists
person: William Bryan
name: Cross of Gold

What does populist party do after cross of gold speech
join democrats

When Bryan becomes popular rich republicans contribute lots and have who elected
McKinley

What does McKinley do
raise tariff

Leader of american imperialism (Pro-Navy)
Alfred Mahan

US first overseas colony for navy base
Pearl Harbor

War that leads to American expansionism
American-Spanish War

What cause starts Spanish-American War
cuba libre

What ship explosion mistakenly interpreted as Spanish fighting and leads Americans to War
Maine

Person that seizes Phillipines because he wants America to become imperial
Theodore Roosevelt

Person that leaves Navy to actually fight in Cuba, gains prestige
Roosevelt

What does America get after Spanish-American War
puerto rico

What year does Spanish-American war end and US keep Phillipines (they don't want to give to imperialists, but they have to educate/civilize)
1898

War that leads to lots of American death from 1898-1902
Phillipine war

Approach to China by McKinley that allows free trade
Open Door

What does US do to get more access to China
fight boxer rebellion

What does Spanish American war do to US govt. (they nearly failed)
create real military


Liberal republicans that support reform
mugwumps

Act that raised tariffs
Mckinley Act

Act that allowed government to get Silver for gold, didn't solve populist requests
Sherman Silver Purchase Act of 1890

When Mckinley elected, he makes what to stop requests for silver
gold standard act of 1900

Leader of Filipinos in Phillipine War
Emilio Aguinaldo

Amendment by US that pressured Cuba into having favorable trade with US (their independence didn't mention US)
Platt Amendment