What were first permanant English settlements?
businesses

What did Europeans try to do (and fail)?
isolate

What did South have that North didn't?
slaves

When was Jamestown founded
1607

What made Jamestown stop being on the brink of dying
help from powhatan
John Smith

Why didn't English want help from powhatan but Capt. John Smith force
pride

When did Natives realize Jamestown might be a problem
Virginia company ships

What makes Jamestown expand
tobacco

System that makes people come to Virginia (where people given land for bringing people and for coming)
headright system

When Pocahontas and Chief Powhatan die what does brother do to send a message to leave
kill quarter of Jamestown

When did first Africans come to Jamestown
portugese raid

When did Jamestown come under the crown
1624

When did William Berkely (Virginia gov.) crush Native American uprising and establish boundary
1644

What did Berkely do to Virginia govt.
keep same people

Why did West people resent Berkely
New people underrepresented

Why did Bacon rebel
no fur trade
boundary line

Who supported Bacon's rebellion
freed indentured servants

What did landowners do after Bacon's rebellion
get slaves

What did landowners do to stop slave rebellions
slave codes

When were slave codes
1705

What did Maryland turn out like
Virginia

What family became Lord Baltimores and got charter from England
Calvert

Who did Calverts get to come to Maryland to make colony successful
Protestants
Catholics

Why did Maryland get religious tolerance
Catholic minority

What did Maryland first have (before switching to headright)
landlords

What was Plymouth religion
puritans

Where did Puritans go before American
holland

What did Pilgrims sign before stepping onto America
Mayflower Compact

What group helped Pilgrims survive in Plymouth
wampanoags

Why did wampanoags help (they knew white bad)
alliance

Why did Plymouth-Native American alliance come under strain
smallpox

Who did Plymouth choose as leader
Bradford

What did all colony leaders have to get
charter

Who created Massachusetts bay company and brought charter to America
John Winthrop

What did Winthrop create ("city upon hill")
strict theocracy

Who helped Masachusetts survive
Pilgrims
wampanoags

Why did Hooker lead people from Masachusetts to establish connecticut
more freedom
better land

Why did Roger Williams separate from Masachusetts and make Rhode Island
buy native land
religious freedom
no england church

Person that challenged Masachusetts clergy and got exiled
Anne Hutchinson

What places did Hutchinson cause people to go to
Maine
New Hampshire

1637 war between natives and british was called
Pequot war

1675 ultimate war with natives vs british
king philip's war

Leader of King Philip's war (called King Philip)
Metacom

What made Metacom lose
Mohawk allies

Major thing that helped natives cause damage in Metacom's war
flintlock rifle

What happened in England 1629-1658
English civil war

Why did English civil war happen
parliament vs monarch

What did Carolinas have to do to bring people
finance expeditions

Who made stratified society constitution for Carolina
John Locke

Where did stratified Carolina constitution not work (poor conditions)
North

What crop did Carolinas focus on
rice

Where did strict people in South Carolina come from
Barbados

Why did duke of york conquer new amsterdam
dutch-english tension

What social structure did New york feature
lots of landlords

When Duke of York became James II what did he give political allies (Carolina people)
New Jersey

What religion was Pennsylvania made for
Quakers

Why was Pennsylvania prosperous
good recruiting

What did counties separating from Pensylvania make
Delaware

Where did most British colonists go at first
Carribean

When did Spanish start conquering California after seeing competition
1760s

Where was tension between English and Spanish (not official) in America
Florida
Carolinas

Why was Georgia made
cut off Spanish
poor people

Where did Europeans accomodate and trade with Native Americans
middle grounds

Where were middle grounds
Western border

Why did Middle Grounds end
increased Europeans

English navigation acts (1660): `1`, `2`, `3`
1: only english trade
2: english tax europe trade
3: customs officials

What did English make to increase colonial presence (combine Masachusetts & others, absolute rule)
dominion of new england

Why was James II kicked out in Glorius revolution
catholic

Who replaced James II
Mary and William