Major movement of early 1900s
progressivism

People that exposed scandals and corruption in railroads, oil, and the government
muckrakers

Focus of progressives
social justice

Effort to make faith into a tool of social reform
Social Gospel

`person` makes `place` which is big house for immigrant community called settlement house
person: Jane Addams
place: Hull house

What did settlement houses lead to
social workers

Movement in which professions create organizations to regulate the people (e.g. Americna Medical Association)
professionalization

Group that led reform
women

Change brought by increasing power of women
divorce rates

Person that writes about how women need to vote early on
Elizabeth Stanton

`person` makes women suffrage organization `name` much more popular (2mil)
person: Anna Shaw
name: NAWSA

Year when states start allowing women to vote
1910

`year`: `amendment` amendment passed to to allow women to vote
year: 1920
amendment: 19th amendment

How did progressives separate municipals from political parties
commissioned city managers

State reforms to reduce influence of party power
initiative
referendum

Thing that allows voters to submit legislation straight to other voters
initiative

Thing that requires state government to tell voters what its doing
referendum

Thing that represented voters beside parties, led to decline in voter turnout
interest groups

Person that challenged Booker Washington and encourage blacks to accept the same as white instead of be content
Du Bois

Organization formed by Du Bois to fight for civil rights
NAACP

Person that helps the NAACP fight lynching
Ida Wells

What movement resurges in early 1900s
temperance

Group that fights against temperance
Women's Christian Temperance Union

`amendment` forces temperance by year `year`
amendment: 18th amendment
year: 1920

Racist movement that gains strength in early 1900s
nativism

Leader of socialist party, gets 1 million votes in 1912
Eugene Debs

Group that committed terror attacks to support socialism, advocated one union for everyone including unskilled labors
wobblies

Person that becomes symbol of reform at national level
Roosevelt

What does roosevelt do
stop some trusts

Government things Roosevelt gives power to
Interstate Commerce Commission
Sherman Antitrust Act

Deal with coal miners on strike by roosevelt that ends the union but gives them some improvements
square deal

Major reform act by Roosevelt
Pure food and drug act of 1907

Nature movement roosevelt supports
conservation

Person that fails presidency after Roosevelt, finally allowing democrats to be president
William Taft

When taft fails who runs for president again
Roosevelt

Who wins election of 1912 against roosevelt and taft
woodrow wilson

What does woodrow wilson support (unlike Roosevelt who was very moderate in this)
extreme antitrust

Bill that could finally cut tariffs like democrats wanted, replaced with income tax from 16th amendment
Underwood-Simmons tariff

Thing wilson creates to help save banks
Federal Reserve Act

Bill to break up trusts
Federal trade comission act

Progressive governer of Wisconsin
Robert Lafollette

Fire that led to building reform from Tammany hall
Triangle Shirtwaist Company

Weak tariff reduction from taft
Payne-Aldrich tariff

Dispute between forest reformer and Taft's new secretary of the interior who was conservative (old guard), leads to Taft discrediting
Pinchot-Ballinger Controversy

Roosevelt's own political party, because he wasn't nominated for Republican party (instead taft was)
Bull Moose party
Progressive party