Major movement of early 1900s
progressivism

People that exposed scandals and corruption in railroads, oil, and the government
muckrakers

Focus of progressives
social justice

Effort to make faith into a tool of social reform
Social Gospel

`person` makes `place` which is big house for immigrant community called settlement house
person: Jane Addams
place: Hull house

What did settlement houses lead to
social workers

Movement in which professions create organizations to regulate the people (e.g. Americna Medical Association)
professionalization

<PAGE 491>