What is roosevelts foreign mission
civilize backwards countries

Complement to monroe doctrine by Roosevelt that allows US to intervene with western governments
Roosevelt Corollary

Country US overthrows for canal
panama

Strategy by Taft to gain control over governments by giving them loans
dollar diplomacy

Place Taft decides to overthrow but Wilson doesn't but it gets overthrown anyways and they are very close to conflict until 1917
Mexico

Thing that forces Americans to side with British
trade

Catalyst for American joining of the war in 1916
Lusitania

Thing that Wilson wants to fight war for
league of nations

Thing that led US to join war
zimmermann telegram

Thing that makes it more attractive to join war
end of russian monarchy

When does US join war
1917

Thing to get 3 million people into army (controversial, 1917)
Selective Service Act

When did war end (because US ended stalemate)
1918

Things significantly developed in WWI
trenches
planes
navy
logistics

Thing to handle wartime economy (e.g. one of these for railroads, one for coal, etc.)
war boards

Thing that makes employers be nice but the workers have to not strike during war
National War Labor Board

Thing made to control public opinion of the war
Comittee on Public Information

Acts to allow government to suppress dissenters
Espionage act of 1917
Sabotage act of 1918
Sedition act of 1918

Things wilson wanted after WWI
league of nations
new boundaries
international conduct

What stops Wilson from getting Treaty of Versailles signed
Republicans

When Wilson goes on national tour to support treaty of versailles what happens that knocks him out for the rest of his presidency
stroke

Major problem after war that led to decline in economy
inflation

When blacks migrate from South for factory labor opened up by whites fighting in the war, what is it called
Great Migration

Riots caused by black teenager getting stoned for going to white beach
Chicago Riots

Person that starts idea of black nationalism and black-owned businesses
Marcus Garvey

Fear of radicals from communist russia in 1919/1920
red scare

Institution made in 1920 for civil rights and also rights of other people
ACLU