In early 1700s what did Americans identify as
british

What decreased indentured servants coming in besides Bacon's rebellion
decreased english birth rate

Life expectancy in America: `A` in North, `B` in South
A: high
B: low

What helped increase birth rates/life expectancy
malaria resistance
more women

Family friends that helped women deliver babies (that docters disliked)
midwives

What common thing caused women to become powerful in Chesapeake
becoming widows

When did people start importing slaves directly to America
1670s

Passage to America for slaves
middle passage

When did German, French, but most commonly Scotch-Irish people start coming to America (because of conflict)
1680s

What was economy in North built around? (still big industry)
surplus goods

Things limiting big industry in America
little labor
small market
transportation
energy

What did colonies lack in the 1700s to start of 1800s
basic technology

Why did Americans embrace consumerism
show social class

What thing in Europe supported consumerism in America
industrial revolution

What was difference between America to Europe class structure
more social mobility

Major slave rebellion in 1739
Stono rebellion

Written agreement within all members of town in New England
covenant

People that townsfolk agreed upon to be leaders (already granted Heaven)
visible saints

Why did salem witchcraft trials occur? (general new england problem)
high tension over religion

Largest colonial cities/ports in 1770s
philadelphia
new york

How was religion in America
very diverse

When did Englightenment come to America
early 1700s

What was great awakening waking up
religion

When was great awakening climax
1740s

Major leader of Great awakening
jonathan edwards

How was literacy for white men in America (high)
half

Most common book besides bible
almanac

When did printers become widespread
1670s

When was first newspaper in boston
1690

Act that causes lots of anger because tax on printed materials
Stamp Act of 1765

When did Massachussets require towns to have schools
1647

By what year did most leaders get education in America (Harvard, Yale, Princeton, etc. existed)
1700

What did most colleges have
Englightenment science

Who spread inoculation against diseases like smallpox as a treatment method (1720s)
Cotton Mather

What did Americans adopt from british politics (trying to replicate everything)
trial by jury

In trial of `person` Americans created `difference`, different from British law
person: John Peter Zenger
difference: free speech
