In early 1700s what did Americans identify as
british

What decreased indentured servants coming in besides Bacon's rebellion
decreased english birth rate

Life expectancy in America: `A` in North, `B` in South
A: high
B: low

What helped increase birth rates/life expectancy
malaria resistance
more women

Family friends that helped women deliver babies (that docters disliked)
midwives

What common thing caused women to become powerful in Chesapeake
becoming widows

When did people start importing slaves directly to America
1670s

Passage to America for slaves
middle passage

When did German, French, but most commonly Scotch-Irish people start coming to America (because of conflict)
1680s