What event brought power to british parliament?
glorious revolution

What was stronger relationship: colonies to britain or colonies to each other? (in 1750)
colonies to britain

`year`: Colonies fight French & Iroquois, `war name`
year: 1754
war name: french and indian war

Where did French and Indian war start
Ohio valley

`year`: `war name` spread from America to Europe between british & french
year: 1756
war name: seven years war

War between British and Spanish that causes Iroquois to allow trade
King George's War

Fort that Washington built at the start of French and Indian War
Fort Necessity

In Seven Years war who was on British side
Prussia
Germany

In Seven Years War who was on French side
Austria-Hungary

What side one in Seven Years war
British
Spain

`major organization` lost power because `religion` lost power in the seven year's war
major organization: the vatican
religion: catholic

Who led british side of seven year's war
william pitt

Practice where British army forcibly enlists colonists
impressment

Why did British want to re-organize America after Seven Years War
fought for America
colonists traded with french
no money

Seven years war `did thing in` America and mobilized `thing` against britain
did thing in: united
thing: grievances

What did Seven years war do to natives
severely weaken