What event brought power to british parliament?
glorious revolution

What was stronger relationship: colonies to britain or colonies to each other? (in 1750)
colonies to britain

`year`: Colonies fight French & Iroquois, `war name`
year: 1754
war name: french and indian war

Where did French and Indian war start
Ohio valley

`year`: `war name` spread from America to Europe between british & french
year: 1756
war name: seven years war

War between British and Spanish that causes Iroquois to allow trade
King George's War

Fort that Washington built at the start of French and Indian War
Fort Necessity

In Seven Years war who was on British side
Prussia
Germany

In Seven Years War who was on French side
Austria-Hungary

What side one in Seven Years war
British
Spain

`major organization` lost power because `religion` lost power in the seven year's war
major organization: the vatican
religion: catholic

Who led british side of seven year's war
william pitt

What did William Pitt do to wartime acts unpopular in America
repeal

Practice where British army forcibly enlists colonists
impressment

Why did British want to re-organize America after Seven Years War
fought for America
colonists traded with french
no money

Seven years war `did thing in` America and mobilized `thing` against britain
did thing in: united
thing: grievances

What did Seven years war do to natives
severely weaken

When does George III come to power
1760

How is British government (and the king himself) when George III
unstable

Person that George III makes prime minister (bad)
George Grenville

Settlers went to `place` after seven years war, got fought with by `group`
place: Ohio valley
group: three fires confederacy

What did British do to fight back against three fires confederacy
smallpox blankets

British proclamation trying to stop conflict and keep trade going, prevents settlers from going past appalachians (unpopular)
Proclamation of 1763

Group of Pennsylvania Frontiersmen that massacre natives, cause distrust
paxton boys

Act that stops colonies from smuggling in sugar and exporting iron and timber with places other than britain
sugar act of 1764

Act that stops colonies from issuing their own paper money (which they did because they had little resources for hard currency)
currency act of 1764

Act that requires Americans to help catch other Americans (join the army) for the British
Mutiny act of 1765

Which group fights for tax relief and financial support for their work
paxton boys

What did the acts of the Grenville administration do to Americans
unite them

What act really enraged Americans because it did not regulate commerce, just increase revenue
Stamp act

Person in House of Burgesses that speaks against George III because of stamp act fears
Patrick Henry

Document that says what Patrick Henry said (including no taxation unless agreed on by Virginia govt.)
Virginia Resolves

Who spoke in British Parliament against the Stamp act
Benjamin Franklin

Group that terrorized agents enforcing stamp act
sons of liberty

Document that accompanies repeal of stamp act that says taxes can be on anything (by new Prime Minister, Marquis of Rockingham)
declaratory act

Why was Vermont broken off by farmers
own New York land they worked

Who replaced Marquis of Rockingham when British people didn't like him
William Pitt

Who did William Pitts job because he had mental illness
Charles Townshend

Tax on lots of things imported from britain
townshend duties

Why did Boston boycott Townshend goods
smuggling ended

After Boycott everything but what Townshend duty was repealed
tea

Event where soldiers accidentally kill 5 people after getting hit by rocks and snowballs (greatly exaggerated)
Boston Massacre

Person that raises outrage over Boston Massacre
samuel adams

Thing Samuel adams creates to hate on Britain, spreads to other colonies
committees of correspondence

People that feared that general public would be influenced by landowners so only landowners should vote
John adams
George washington

Theory in which people don't need representation because Government is acting for them
virtual representation

Difference between virtual representation of British citizens and American citizens
distance

Place that allows people to talk about politics and make decisions
taverns

What act gave British East India Company no tax on tea and led to first mass boycotts
Tea Act of 1773

Women that led tea boycott
daughters of liberty

Event where dissenters throw tea into the harbor (spread elsewhere too)
Boston tea party

Why did British send first soldiers
confiscate gunpowder

Who warned minutemen in Boston
Paul revere
william dawes

What happened to Britain while travelling to and from gunpowder (it was moved)
heavy losses

These soldiers came from `place` and went to `target` (where gunpowder was)
place: lexington
target: concord

What idea spread, starting American revolution
british fired first