What did Second Continental Congress agree on
fighting war

What did Second Continental Congress not agree on: `idea 1` vs `idea 2`
idea 1: freedom
idea 2: reconcil with Britain

What made people want freedom
cost of war

`Document` in 1776 that says English constitution is a problem, not taxes, need freedom, by `author`
Document: Common Sense
author: Thomas Paine

Parts of Declaration of Independence: `1`, `2`
1: John Locke Ideas
2: Grievances

National level document for the union after declaration of independence
articles of confederation

When Continental currency fails, where does Congress get financing from
borrow from other countries

Congress created central army with what commander
George Washington

Who did George Washington bring to increase power
foreign experts

People fighting British: `support`, people helping British: `anti`
support: patriots
anti: loyalists

First phase of Revolutionary war: `name`, British start in Boston, suffer losses, go to Halifax
name: New England

Second phase: `name`, winter section, British try to fight the entire North instead of quell rebellions
name: mid-atlantic region

What did Washington do to hurt British while they were settled in the winter (phase 2)
cross the delaware

What did Howe (leader of British) do to hopefully stop rebels but continental congress just moved (phase 2)
capture philadephia

Howe tells who to come South while he goes North, capturing along the way, but then Howe goes South and he is left to fight for himself
Burgoyne

Burgoyne surrendered because `reason` in `place`
reason: no resources
place: saratoga

Country that supported Americans, provided supplies
France

Final phase of war: `name`, give up on North
name: The South

Fighting method introduced in "Revolutionary" war
Guerilla

Person that fought heavily against British but eventually defected, shocked Americans
Arnold

Person that led American force in the South
Nathaniel Greene

Where did Southern army eventually go to and surrender because surrounded
yorktown

Who got favorable treaty with the British while quelling French-Spanish relations
Benjamin Franklin

Churches that got weak after Revolution
anglican
quakers

Slave-related law spreading through North
gradual emancipation

Tension occurs between Americans and which group because of their support of British in Revolution
Native americans

Person that advocated womens rights to John Adams
Abigail Adams

What happened to American trade after Revolution
cut off from British

Difference between American and British constitutions
written down

Difference in old state constitutions and new ones
strong executive

Rule that splits west land into squares and sells them to towns, uses money to make schools and saves some for public land
Ordinance of 1785

Major battle between Americans and Native Americans over Northwest land, won by Americans
Battle of Fallen Timbers

Major problem with confederation
cant pay debt

Group of farmers that rebelled against debts
shay's rebellion