Thing that pushed Americans to make stronger government since Articles of Confederation couldn't stop it
shay's rebellion

Person that starts constitutional convention
Alexander Hamilton

Plan that dictated overall constitution, argued for tripartite government
virginia Plan

Appeasement of Virginia Plan for small states
senate

Compromise to allow senate and slaves for 3/5th of Person
great compromise

Person that made Virginia Plan and wrote most of the constitution
James Madison

People that supported strong national government
federalists

Document made for Antifederalists
bill of rights

Only group that could legally be citizens
white

Essays written by Hamilton, Madison, Jay under `name` (pseudonym), called `documents`
name: Publius
documents: Federalist Papers

Thing that antifederalists in large states (Virginia, New York) wanted before ratifying constitution
bill of rights

In what year was George Washington elected as president
1789

Congress created what departments under executive branch
state
treasury
war

Group that believed in rural, agrarian nation with less powerful government
republicans

Way for Hamilton to create permanent debt that gave wealthy people stake in government
bonds

Thing that Hamilton wanted to do to state debt, got it in exchange for creation of Washington D.C.
nationalize

Major speakers of republicans
jefferson
Madison

Treaty to prevent war with Britain and keep trade when they seized American ships to fight france
Jay's Treaty

Leader of Federalists since Hamilton had too many enemies
John Adams

Conflict with France over them seizing American ships, led to creation of Navy, france didn't negotiate until napoleon
Quasi war

Act that makes it harder to come to US
alien act

Act that makes it illegal to lie about government
sedition act

Thing hurt by Alien and Sedition acts
republicans

Revolution where Jefferson elected, makes government mostly republican (from federalist)
revolution of 1800