Idea about population central to Republican vision
Educated public

What were schools actually open to during Jeffersonian era
Rich white men

Idea that led to some educated women and sped up female education
Republican mother

Person that published essay on why women get education
Judith Sargent Murray

`Thing` spreads through medicine during Jeffersonian era, leads to less `group` in profession
Thing: Science
group: women

Person that argued that America will become more culturally advanced than Europe, supported education
Noah webster

When did second great awakening happen (after deism and other science based religion was spreading)
1801

Place where massive revivalism (great awakening) meeting happened in 1801
Cane ridge

Religious idea that goes away in second great awakening
Predestination

Alcoholic that becomes religious and spreads agriculture to native Americans
Handsome lake

Person that brought textile mills to America from London
Samuel slater

American inventor that makes cotton gin
Eli whitney

Thing that expands as a result of cotton gin
Slaves in south

Idea in technology introduced by Eli Whitney
Interchangeability

New social idea after industrialization
Faraway ceo

Thing missing for early american industrialization
Transportation

Person that introduces steamboat to America that’s actually good
Robert fulton

Hobby that spreads to take mind away from industrialization, especially for elites
Horse racing

Idea that jefferson conveys about himself
Common person

National things that jefferson reduces
Spending
Debt
Army

Case in which Congress rules its ability to force commissions unconstitutional, but in doing that gives its ability to declare acts from congress unconstitutional
Marbury v Madison

When France (Napoleon) is taking over Louisiana from the Spanish and eliminating American rights, what does Jefferson do to avoid conflict with France
Louisiana purchase

Expedition Jefferson makes to understand what is west of the US and what they got in the Louisiana purchase
Lewis and Clark

What does group of federalists called Essex Junto decide they need to not lose power after Louisiana Purchase makes more states
Secession

When Aaron Burr supports secession in New York but Hamilton doesn't, what do they do
Duel

Who dies because of duel
Hamilton

Who believed Burr was trying to conquer the southwest and make a new country (even though this may have not been true), had him arrested
Jefferson

Things that combine to make war of 1812
Napoleonic wars
Native american resistance

What did French and British do to America during napoleonic wars
Impose trade restrictions

What did British do to American ships to make sure their navy doesn't lose everyone during their blockades of Europe
Impressment

What does Jefferson do to stop war with Britain after Americans outraged at British ships doing impressment and British refuse to stop it
Embargo act of 1807

When does Jefferson repeal embargo act after Americans mad, it induces depression
1808

Person in charge of making treaties with Native Americans over western lands
William Henry Harrison

Person that unites Native Americans over their religion and helps them fight together against the Americans, gets alliance with British in Canada
Tecumseh

While Harrison destroyed lots of Tecumseh's forces, by what year did he begin raids of western places
1812

What did people in South do to Baton Rouge, Florida
Conquer

What stops Annexation of florida that President Madison promised
Spanish british alliance

When were representatives eager to fight Britain elected
1810

Where did Americans successfully fight Native Americans and British and defeat Tecumseh
Great lakes

Where did Americans fight even more successfully under leadership of Andrew Jackson
South of Tennessee and Florida

When did Napoleon surrender, causing British to invade America and burn down white house and others
1814

Where do British try to invade in Baltimore after burning down White House, but are successfully blocked by Americans, leading to Star-Spangled Banner
Fort McHenry

Convention where Federalists talk about secession but mostly just want amendments to make New England powerful
Hartford Convention

Treaty that ends war of 1812, little happens besides end of fighting
Treaty of Ghent

What breaks apart after Treaty of Ghent
Intertribal alliances