During war state banks make inconsistent currency, so what does congress do
second national bank

What increases during war of 1812 because cut off from trade
manufacturing

Person that vetoes building roads without amendment
madison

Why do people go west
more land

What did people do after building quick farms in the west
sell for profit

Where did wealthy planters go
cleared parts of old southwest

Area where cotton grows well due to dark soil
black belt

After war of 1812 what entered fur trapping space
white trappers

When Jefferson gets his secretary of state elected, who is next president
James Monroe

Who does Jefferson make his secretary of state
John Quincy Adams

After Monroe is elected what starts, ending Federalist party
era of goody feelings

When Calhoun (secretary of war) tells Andrew Jackson to stop Seminole raids, what does he starts
Seminole wars

Treaty that Adams negotiates after showing power through raids in Seminole wars, gets all of Florida from Spain
Adams-Onis Treaty

Event where national government starts tightening credit that fueled land expansion, leading to collapsing state banks and depression
panic of 1819

Amendment suggested to Missouri to get rid of slavery since North doesn't want slaves, led to lots of conflict between North and South
tallmadge amendment

Compromise between North and South that led to line in wich slaves are below, reduced tension
Missouri Compromise

Speaker of house that suggests Missouri compromise
Henry Clay

John Marshall pushes what ideal on government
Federalist

Case where John Marshall supports contracts even if they are shady, strengthening economy
Fletcher v. Peck

Case where John Marshall supports national bank
McCulloch v. Maryland

Case where John Marshall gives congress power to regulate state commerce
Gibbons v. Ogden

Case where John Marshall gives US power to make treaties with Natives and states can't interfere
Worcester v. Georgia

When Spanish colonies revolt, America gives them power with what
Monroe doctrine

What does Monroe doctrine say (even though made by John Quincy Adams)
no europeans can control americas

`year`: Democrat-Republican party splits into Democratic (`democrat idea`), and Republican (`republican idea`)
year: 1828
democrat idea: Jeffersonian
republican idea: Federalist

Idea by Henry Clay to make a program for factories and farms by increasing tariff and bank power
American System

When jackson was elected after Adams what did they call it
era of the common man