Type of people allowed to vote after Jackson (huge expansion)
white men

Rebellion in Rhode Island where new constitution put in place but old government imprisions the people
dorr Rebellion

`person` wrote `book` about life in America in various groups in the 1830s
person: Alexis de Tocqueville
book: Democracy in America

Party against Jackson
Whigs

Party that follows Jackson
Democrats

Difference between Jackson and Jefferson
no consistent ideology

System where jobs are given to winning party in government
spoils system

Controversy with Jacksons VP was over what idea
nullification

Who was Jacksons VP
John Calhoun

Rival of Calhoun
Martin Van Buren

`year`: `Debate` debate by South Carolina representative over nullification and power of East
year: 1830
Debate: Webster-Hayne

Person that solves possible military intervention in South Carolina when they nullify Tariff of Abominations (he gradually lowers tariff to 1816 levels)
Henry Clay

Brutal war where whites keep on attacking when Native Americans surrender
Black Hawk war

Group of tribes that somewhat adopted Western culture
five civilized tribes

Act which authors financing of negotiations to remove Native Americans
Indian Removal Act

When Cherokee make deal but many dont follow they are sent to `place` (`informal name`) in `event name`
place: Oklahoma
informal name: Indian Territory
event name: Trail of Tears

Person that ran National Bank after 1832
Nicholas Biddle

Factions against Bank: `group` that believes state banks should issue money freely, `group 2` that believes only gold is viable
group: soft money
group 2: hard money

War between Henry Clay, Daniel Webster and Jackson over national bank
bank war

When Jackson re-elected because people don't care about bank war and so don't vote henry clay, what does he try to do
withdraw federal deposits

Person that Jackson makes secretary to withdraw funds
Roger B. Taney

When bank runs out of funds and people hate it when it tries to get money when does it end because no recharter
1836

When Marshall dies who becomes chief justice
Taney

What does Taney do in Charles River Bridge v. Warren Bridge
amend contracts

System of politics with two parties
second party system

Group of radical democrats that riot against elite
loco focos

Person that succeeded Jackson
Van Buren

Why did Whigs fail even though they had a good amount of support
no single leader

When economic boom of 1836 makes government give out lots of money, what law do they enact to require currencies backed by gold and silver to be repaid
specie circular

Result of Specie circular
panic of 1837

Person whigs chose after 1840 (where depression from Van Buren happening)
William Henry Harrison

Newspapers for common people used to spread election info
penny press

When harrison dies of Pneumonia who replaces him (Whigs wons)
John Tyler

Who does Tyler replace original whigs with
former democrats

Things that make Tensions between Britain and America rise: `state border`, `slave ship` accepted by British and slaves freed, `supply ship` to rebels in Canada burned and one American dies
state border: Maine
slave ship: Creole
supply ship: Caroline

Treaty to lower tensions with British
Webster-Ashburton Treaty

Person in 1844 the Whigs lose to
James K. Polk