Similarities between China and Rome
control entire world
invest in infrastructure
gods help rulers
absorb other faith
hurt environment

Differences between China and Rome (citizenship, religion, language, education, government)
romans distinct from conquered
chinese religion not supported by state
chinese language for elites
chinese have schools
rome believes good laws
china believes good men

How did the Roman and Chinese empires end?
too big
no new technology
rivalry among elite
nomads
epidemics

Why did China reconstruct one large state but not Europe?
People share cultural identity