`time` BCE: Classical greece, 2-`pop`mil people
time: 750
pop: 3

Made up of `thing`, very competitive, occurred due to them living on `landform`
thing: city-states
landform: peninsula

Greek leaders came from `council`, `count` wealthy people over `age`, served for life
council: Council of Elders
count: 28
age: 60

Sparta had lots of `thing`, conquered people that lived like slaves
thing: Helots

`time` BCE: First Olympics, stop fighting every 4 years for Olympics
time: 776

`time` BCE: Solon pushes `city` politics to democracy instead of Aristocratic families ruling, rights extended more by `one` and `two`
time: 594
city: Athenian
one: Cleisthenes
two: Pericles

`thing`: `kind` democracy (not representative)
thing: Athenian Democracy
kind: Direct

Who couldn't vote in Athenian democracy?
Women
Slaves
Foreigners

`time` BCE: Greeks expand looking for food all across border of Mediterranean
time: 500

`start`-`end`: Greco-Persian wars, Greeks of `place` (Anatolian) revolt, was `period`
start: 499
end: 449
place: Ionia
period: Golden Age of Greek Culture

When did the Persians send expeditions against the Greeks?
490 BCE
480 BCE

`time` BCE: Even poor people can hold office because office gets paid
time: 450

`start`-`end` BCE: Athens fights Sparta, loses in `war`
start: 431
end: 404
war: Peloponnesian

`time` BCE: King `name` unifies Greece, ends city-states and freedom
time: 338
name: Phillip II

`start`-`end` BCE: 10-year expedition of Alexander the Great, Persepolis ruined, Alexander is "king of Asia" and pharaoh, was `age`
start: 334
end: 323
age: 24

`start`-`end` BCE: `period`, Greek Culture spreads everywhere, mostly through cities they establish (established cities resembled older empires, no `thing`), Greek people are `adjective` compared to conquered
start: 323
end: 30
period: Hellenistic
thing: democracy
adjective: elite