`start`-`end` BCE: `name` Dynasty, famous leaders are `one` and `two`
start: 550
end: 330
name: Achaemenid
one: Cyrus
two: Darius

The Persian Empire had 30-`pop`mil people, the `leader name` was approached with `thing`, when the leader dies people `one`, `two`.
pop: 50
leader name: monarch
thing: ritual
one: shave
two: put out fires

`thing`: Gave Persian kings power
thing: Ahura Mazda

Persian kings placed `people`, Persian governers for each of the `count` provinces, kept local officials, had `thing` everywhere
people: Satraps
count: 23
thing: spies

`time` BCE: `leader` wins respect of Jews
time: 539
leader: Cyrus

Persian capitals?
Susa
Persepolis