FITT Principal for cardio: `F` (`f target`), `I` (`i target`), `T` (t target), `T2` (`t2 target`)
F: Frequency
f target: 3-5 per week
I: Intensity
i target: 60-85% max hr
T: Time
t target: 20-30 min
T2: Type
t2 target: running

Muscle of chest
pectorals

Flat muscle used for pulling
latissimus dorsi

Triangle muscle under traps going from spine to scapula
rhomboids

Muscle between shoulder and neck
Trapezius

Muscle used to rotate shoulder with rotator cuffs
Teres

Muscle that straightens and rotates back
Erector Spinae

Muscle for bringing things toward body in arms
bicep

Muscle for straightening arms
tricep

Muscle to lift arms
deltoids

`forward` deltoid, `middle` deltoid, `back` deltoid
forward: anterior
middle: medial
back: posterior

Muscle used for rotating body
obliques

Muscle used to move upper leg
gluteus

Muscles in rib cage that stabilize shoulder
Serratus

Muscle used to bend knees on back of leg
hamstrings

Muscles used to bend knees on front of leg
quadriceps

Muscle used to bend ankle
gastrocnemius

Muscle thats primarily moving in an action
agonist

Muscle that moves against agonist
antagonist

Set of agonist, then antagonist
superset

Muscle contraction in which no movement happens, just tension
isometric

Muscle contraction in which movement occurs
isotonic contraction

Muscle contraction in which muscle length decreases (e.g. going up in squat)
concentric

Muscle contraction in which length increases (e.g. going down in squat)
eccentric

Biceps antagonist
triceps

Gluteus maximus antagonist
hip flexors

Muscle used to lift leg up (hip flexor)
psoas

Quadricep antagonist
hamstrings

Pectorals antagonist
latissimus dorsi

Gastrocnemius antagonist
tibialis

Muscle that moves leg to the side away from body
abductor

Muscle that moves leg to the side towards body
adductor

Abductor antagonist
adductor

Abdominals antagonist
erector Spinae

Barbell with kinks in the handle
ez bar

Rep where your partner helps you
forced reps

Training where you increase weight and then climax and then decrease reps
pyramid Training

Training where you rotate through exercises that target different parts
circuit training

Benefit of warming up and cooling down
lower soreness

What to do to recover from cardio
drink water

What to do to recover from muscle exercises
roll out

Recovery where you cool down/walk between sets
active Recovery

Recovery where you don't do anything
passive recovery

RICE: `r`, `i`, `c`, `e`
r: rest
i: ice
c: compression
e: elevation

SMART: `s`, `m`, `a`, `r`, `t`
s: specific
m: measurable
a: achievable
r: relevant
t: timely

Health related components of fitness
body composition
flexibility
muscular strength
muscular endurance
cardiorespiratory endurance

Skill related components of fitness
agility
speed
power
balance
coordination
reaction time

Principles of training
overload
specificity
reversibility
variance
progression

Principle for FITT
overload

Principle where if you don't train you lose fitness
reversibility

Principle for not running 5k for sprints
specificity

Principle for doing different exercise when resting
variance

Principle for increasing work over time
progression

One minute heart rate after exercise name
recovery heart rate

Parts of body composition
fat
bone
muscle

Amount of energy body uses to survive (maintain base metabolism)
caloric expenditure

Another name for caloric expenditure
metabolic rate

Amount of force you can hold isometrically
static strength

Amount of weight you can move over a distance (e.g. weightlifting)
strength

Amount of work you can do in a certain time (strength * speed)
power

Speed vs velocity (what does velocity have)
direction