What caused increase in independence
Britain grew weaker

What did Ghana base country on
nationalism

Common problem in African dictatorships
corruption

Why did Algeria have to fight a war and lose thousands for independence
large French population

What group in South Vietnam led to American loss of Vietnam
viet cong

One of first examples of Non-aligned action influenced by cold war
suez canal

Group in Nigeria to temporarily get obedience (Christian)
Igbos

Why does Quebec want to be separate
french vs british