How long does renewed driver license last
6 years

How long to comply with Failure to Appear (FTA)
45 days

Causes of crashes: `1`, `2`, `3`, `4`, `5`, `6`, `7`
1: impairment
2: running off
3: speeding
4: young driver
5: distraction
6: unrestrained
7: intersection error

Things to check on car
brakes
lights
windshield
tires
steering
exhaust
suspension
engine
horn
trunk

How much highway litter comes from unsecured loads
40%

Age to go in the back seat
13

Age to get out of child safety restraint
8

Height to get out of child safety restraing
4'9

Age to go in rear facing seat
2

Stop on yellow light if
safe

How long does it take train to stop 
1 mile

What type of line is on outer edge of road
solid white

What type of line is on inner edge of road
solid yellow

What type of line means you can pass on inner edge of road
dashed yellow

Max distance you can travel in twow-way left turn lanes (the U-turn things)
300 feet

Emergency zone length
200 feet

Speed limit on beach
25mph

Max parking infraction amount
$250

At intersection without rules you must
yield

What do you wait for before going past schoolbus when red lights turn off
no children

Order in getting out of car: `1`, `2`, `3`
1: check rear-view
2: check side-view
3: dutch reach

Min distance to park away from traffic signal/stop sign/yield sign
30 feet

Min distance to park away from pedestrian safety zone
20 feet

Min distance to park away from fire hydrant
15 feet

Min distance to park away from railroad crossing
50 feet

Min distance to park away from fire station driveway on opposite side of street
75 feet

Min distance to park away from fire station driveway on close side of street
20 feet

Min distance to park from driveway/alley/private road/lowered sidewalk curb
5 feet

Meaning of white curb
short stop

Meaning of yellow/red curb
restricted

Max distance to park away from the curb
12 inches

Speed limit in school zone
20mph

Speed limit in cities and towns
25mph

Speed limit on county road
50mph

Speed limit on state highway
60mph

Inattentional blindness also known as
distracted driving

Distance to scan ahead
15 seconds

Distance to turn on turn signal
100 feet

To be in front of truck, have one car length for every `speed` used
speed: 10mph

What to do while backing
yield

Distance to dim high beams at
500 feet

Distance to use low beams at
300 feet

Distance to place emerency flares behind vehicle
200-300 feet

Speed you have good traction in rain
35mph

Speed you start hydroplaning in
50mph

Slow moving vehicles with sign go at
25mph

At fast speeds how far do you need to see ahead
400 feet

Rule for driving over 30 mph
four second rule

When person behind you wants to pass what do you do
slow down

Time needed to pass at 55mph (make sure oncoming traffic is this far)
10 seconds

Major cause of running of the road
speeding

Illegal blood alcohol level
.08

Illegal THC level
5.00

License suspended for how long in first violation
90 days

License suspended for how long in second violation
2 years

Probationary license time
5 years

What to do if lack of brake pressure
pump brakes

What to do if tire blowout
hold wheel tightly

If engine stalls do what
hold wheel tightly

If gas pedal is stuck
switch to neutral

Options for collision
stop
turn
speed up

Things to be ready to adjust in intersection
speed
lane position